FROM goodrainapps/alpine:3.4

ADD rainbond-gateway /run/rainbond-gateway
ADD entrypoint.sh /run/entrypoint.sh
ADD openresty-1.13.6.1.tar.gz /

ENV RELEASE_DESC=5.0-8eea0849-2018-11-21-13
ENV OPENRESTY_HOME=/usr/local/openresty
ENV PATH="${PATH}:${OPENRESTY_HOME}/nginx/sbin"

EXPOSE 8080

ENTRYPOINT ["/run/entrypoint.sh"]
