// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app_runtime_server.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ServiceRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceRequest) Reset()         { *m = ServiceRequest{} }
func (m *ServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceRequest) ProtoMessage()    {}
func (*ServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{1}
}
func (m *ServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRequest.Unmarshal(m, b)
}
func (m *ServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRequest.Marshal(b, m, deterministic)
}
func (dst *ServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRequest.Merge(dst, src)
}
func (m *ServiceRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceRequest.Size(m)
}
func (m *ServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRequest proto.InternalMessageInfo

func (m *ServiceRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type ServicesRequest struct {
	ServiceIds           string   `protobuf:"bytes,1,opt,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServicesRequest) Reset()         { *m = ServicesRequest{} }
func (m *ServicesRequest) String() string { return proto.CompactTextString(m) }
func (*ServicesRequest) ProtoMessage()    {}
func (*ServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{2}
}
func (m *ServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServicesRequest.Unmarshal(m, b)
}
func (m *ServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServicesRequest.Marshal(b, m, deterministic)
}
func (dst *ServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServicesRequest.Merge(dst, src)
}
func (m *ServicesRequest) XXX_Size() int {
	return xxx_messageInfo_ServicesRequest.Size(m)
}
func (m *ServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServicesRequest proto.InternalMessageInfo

func (m *ServicesRequest) GetServiceIds() string {
	if m != nil {
		return m.ServiceIds
	}
	return ""
}

type TenantRequest struct {
	TenantId             string   `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantRequest) Reset()         { *m = TenantRequest{} }
func (m *TenantRequest) String() string { return proto.CompactTextString(m) }
func (*TenantRequest) ProtoMessage()    {}
func (*TenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{3}
}
func (m *TenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantRequest.Unmarshal(m, b)
}
func (m *TenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantRequest.Marshal(b, m, deterministic)
}
func (dst *TenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantRequest.Merge(dst, src)
}
func (m *TenantRequest) XXX_Size() int {
	return xxx_messageInfo_TenantRequest.Size(m)
}
func (m *TenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TenantRequest proto.InternalMessageInfo

func (m *TenantRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

type StatusMessage struct {
	Status               map[string]string `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StatusMessage) Reset()         { *m = StatusMessage{} }
func (m *StatusMessage) String() string { return proto.CompactTextString(m) }
func (*StatusMessage) ProtoMessage()    {}
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{4}
}
func (m *StatusMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusMessage.Unmarshal(m, b)
}
func (m *StatusMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusMessage.Marshal(b, m, deterministic)
}
func (dst *StatusMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusMessage.Merge(dst, src)
}
func (m *StatusMessage) XXX_Size() int {
	return xxx_messageInfo_StatusMessage.Size(m)
}
func (m *StatusMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StatusMessage proto.InternalMessageInfo

func (m *StatusMessage) GetStatus() map[string]string {
	if m != nil {
		return m.Status
	}
	return nil
}

type DiskMessage struct {
	Disks                map[string]float64 `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DiskMessage) Reset()         { *m = DiskMessage{} }
func (m *DiskMessage) String() string { return proto.CompactTextString(m) }
func (*DiskMessage) ProtoMessage()    {}
func (*DiskMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{5}
}
func (m *DiskMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskMessage.Unmarshal(m, b)
}
func (m *DiskMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskMessage.Marshal(b, m, deterministic)
}
func (dst *DiskMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskMessage.Merge(dst, src)
}
func (m *DiskMessage) XXX_Size() int {
	return xxx_messageInfo_DiskMessage.Size(m)
}
func (m *DiskMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DiskMessage proto.InternalMessageInfo

func (m *DiskMessage) GetDisks() map[string]float64 {
	if m != nil {
		return m.Disks
	}
	return nil
}

type ServiceAppPodList struct {
	Pods                 []*ServiceAppPod `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ServiceAppPodList) Reset()         { *m = ServiceAppPodList{} }
func (m *ServiceAppPodList) String() string { return proto.CompactTextString(m) }
func (*ServiceAppPodList) ProtoMessage()    {}
func (*ServiceAppPodList) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{6}
}
func (m *ServiceAppPodList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceAppPodList.Unmarshal(m, b)
}
func (m *ServiceAppPodList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceAppPodList.Marshal(b, m, deterministic)
}
func (dst *ServiceAppPodList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceAppPodList.Merge(dst, src)
}
func (m *ServiceAppPodList) XXX_Size() int {
	return xxx_messageInfo_ServiceAppPodList.Size(m)
}
func (m *ServiceAppPodList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceAppPodList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceAppPodList proto.InternalMessageInfo

func (m *ServiceAppPodList) GetPods() []*ServiceAppPod {
	if m != nil {
		return m.Pods
	}
	return nil
}

type ServiceAppPod struct {
	ServiceId            string                `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	DeployId             string                `protobuf:"bytes,2,opt,name=deploy_id,json=deployId,proto3" json:"deploy_id,omitempty"`
	DeployType           string                `protobuf:"bytes,3,opt,name=deploy_type,json=deployType,proto3" json:"deploy_type,omitempty"`
	PodName              string                `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodIp                string                `protobuf:"bytes,5,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	PodStatus            string                `protobuf:"bytes,6,opt,name=pod_status,json=podStatus,proto3" json:"pod_status,omitempty"`
	Containers           map[string]*Container `protobuf:"bytes,7,rep,name=containers,proto3" json:"containers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ServiceAppPod) Reset()         { *m = ServiceAppPod{} }
func (m *ServiceAppPod) String() string { return proto.CompactTextString(m) }
func (*ServiceAppPod) ProtoMessage()    {}
func (*ServiceAppPod) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{7}
}
func (m *ServiceAppPod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceAppPod.Unmarshal(m, b)
}
func (m *ServiceAppPod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceAppPod.Marshal(b, m, deterministic)
}
func (dst *ServiceAppPod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceAppPod.Merge(dst, src)
}
func (m *ServiceAppPod) XXX_Size() int {
	return xxx_messageInfo_ServiceAppPod.Size(m)
}
func (m *ServiceAppPod) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceAppPod.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceAppPod proto.InternalMessageInfo

func (m *ServiceAppPod) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *ServiceAppPod) GetDeployId() string {
	if m != nil {
		return m.DeployId
	}
	return ""
}

func (m *ServiceAppPod) GetDeployType() string {
	if m != nil {
		return m.DeployType
	}
	return ""
}

func (m *ServiceAppPod) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *ServiceAppPod) GetPodIp() string {
	if m != nil {
		return m.PodIp
	}
	return ""
}

func (m *ServiceAppPod) GetPodStatus() string {
	if m != nil {
		return m.PodStatus
	}
	return ""
}

func (m *ServiceAppPod) GetContainers() map[string]*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type Container struct {
	ContainerName        string   `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	MemoryLimit          int64    `protobuf:"varint,2,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{8}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *Container) GetMemoryLimit() int64 {
	if m != nil {
		return m.MemoryLimit
	}
	return 0
}

type DeployInfo struct {
	Namespace            string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Statefuleset         string            `protobuf:"bytes,2,opt,name=statefuleset,proto3" json:"statefuleset,omitempty"`
	Deployment           string            `protobuf:"bytes,3,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Pods                 map[string]string `protobuf:"bytes,4,rep,name=pods,proto3" json:"pods,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Services             map[string]string `protobuf:"bytes,5,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Endpoints            map[string]string `protobuf:"bytes,6,rep,name=endpoints,proto3" json:"endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Secrets              map[string]string `protobuf:"bytes,7,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Ingresses            map[string]string `protobuf:"bytes,8,rep,name=ingresses,proto3" json:"ingresses,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Replicatset          map[string]string `protobuf:"bytes,9,rep,name=replicatset,proto3" json:"replicatset,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Status               string            `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeployInfo) Reset()         { *m = DeployInfo{} }
func (m *DeployInfo) String() string { return proto.CompactTextString(m) }
func (*DeployInfo) ProtoMessage()    {}
func (*DeployInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{9}
}
func (m *DeployInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployInfo.Unmarshal(m, b)
}
func (m *DeployInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployInfo.Marshal(b, m, deterministic)
}
func (dst *DeployInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployInfo.Merge(dst, src)
}
func (m *DeployInfo) XXX_Size() int {
	return xxx_messageInfo_DeployInfo.Size(m)
}
func (m *DeployInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeployInfo proto.InternalMessageInfo

func (m *DeployInfo) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeployInfo) GetStatefuleset() string {
	if m != nil {
		return m.Statefuleset
	}
	return ""
}

func (m *DeployInfo) GetDeployment() string {
	if m != nil {
		return m.Deployment
	}
	return ""
}

func (m *DeployInfo) GetPods() map[string]string {
	if m != nil {
		return m.Pods
	}
	return nil
}

func (m *DeployInfo) GetServices() map[string]string {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *DeployInfo) GetEndpoints() map[string]string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *DeployInfo) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *DeployInfo) GetIngresses() map[string]string {
	if m != nil {
		return m.Ingresses
	}
	return nil
}

func (m *DeployInfo) GetReplicatset() map[string]string {
	if m != nil {
		return m.Replicatset
	}
	return nil
}

func (m *DeployInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type TenantResource struct {
	CpuRequest            int64    `protobuf:"varint,1,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	CpuLimit              int64    `protobuf:"varint,2,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryRequest         int64    `protobuf:"varint,3,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	MemoryLimit           int64    `protobuf:"varint,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	RunningAppNum         int64    `protobuf:"varint,5,opt,name=running_app_num,json=runningAppNum,proto3" json:"running_app_num,omitempty"`
	UnscdCpuReq           int64    `protobuf:"varint,6,opt,name=unscd_cpu_req,json=unscdCpuReq,proto3" json:"unscd_cpu_req,omitempty"`
	UnscdCpuLimit         int64    `protobuf:"varint,7,opt,name=unscd_cpu_limit,json=unscdCpuLimit,proto3" json:"unscd_cpu_limit,omitempty"`
	UnscdMemoryReq        int64    `protobuf:"varint,8,opt,name=unscd_memory_req,json=unscdMemoryReq,proto3" json:"unscd_memory_req,omitempty"`
	UnscdMemoryLimit      int64    `protobuf:"varint,9,opt,name=unscd_memory_limit,json=unscdMemoryLimit,proto3" json:"unscd_memory_limit,omitempty"`
	RunningAppThirdNum    int64    `protobuf:"varint,10,opt,name=running_app_third_num,json=runningAppThirdNum,proto3" json:"running_app_third_num,omitempty"`
	RunningAppInternalNum int64    `protobuf:"varint,11,opt,name=running_app_internal_num,json=runningAppInternalNum,proto3" json:"running_app_internal_num,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *TenantResource) Reset()         { *m = TenantResource{} }
func (m *TenantResource) String() string { return proto.CompactTextString(m) }
func (*TenantResource) ProtoMessage()    {}
func (*TenantResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{10}
}
func (m *TenantResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantResource.Unmarshal(m, b)
}
func (m *TenantResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantResource.Marshal(b, m, deterministic)
}
func (dst *TenantResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantResource.Merge(dst, src)
}
func (m *TenantResource) XXX_Size() int {
	return xxx_messageInfo_TenantResource.Size(m)
}
func (m *TenantResource) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantResource.DiscardUnknown(m)
}

var xxx_messageInfo_TenantResource proto.InternalMessageInfo

func (m *TenantResource) GetCpuRequest() int64 {
	if m != nil {
		return m.CpuRequest
	}
	return 0
}

func (m *TenantResource) GetCpuLimit() int64 {
	if m != nil {
		return m.CpuLimit
	}
	return 0
}

func (m *TenantResource) GetMemoryRequest() int64 {
	if m != nil {
		return m.MemoryRequest
	}
	return 0
}

func (m *TenantResource) GetMemoryLimit() int64 {
	if m != nil {
		return m.MemoryLimit
	}
	return 0
}

func (m *TenantResource) GetRunningAppNum() int64 {
	if m != nil {
		return m.RunningAppNum
	}
	return 0
}

func (m *TenantResource) GetUnscdCpuReq() int64 {
	if m != nil {
		return m.UnscdCpuReq
	}
	return 0
}

func (m *TenantResource) GetUnscdCpuLimit() int64 {
	if m != nil {
		return m.UnscdCpuLimit
	}
	return 0
}

func (m *TenantResource) GetUnscdMemoryReq() int64 {
	if m != nil {
		return m.UnscdMemoryReq
	}
	return 0
}

func (m *TenantResource) GetUnscdMemoryLimit() int64 {
	if m != nil {
		return m.UnscdMemoryLimit
	}
	return 0
}

func (m *TenantResource) GetRunningAppThirdNum() int64 {
	if m != nil {
		return m.RunningAppThirdNum
	}
	return 0
}

func (m *TenantResource) GetRunningAppInternalNum() int64 {
	if m != nil {
		return m.RunningAppInternalNum
	}
	return 0
}

type AddThirdPartyEndpointsReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	IsOnline             bool     `protobuf:"varint,5,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddThirdPartyEndpointsReq) Reset()         { *m = AddThirdPartyEndpointsReq{} }
func (m *AddThirdPartyEndpointsReq) String() string { return proto.CompactTextString(m) }
func (*AddThirdPartyEndpointsReq) ProtoMessage()    {}
func (*AddThirdPartyEndpointsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{11}
}
func (m *AddThirdPartyEndpointsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddThirdPartyEndpointsReq.Unmarshal(m, b)
}
func (m *AddThirdPartyEndpointsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddThirdPartyEndpointsReq.Marshal(b, m, deterministic)
}
func (dst *AddThirdPartyEndpointsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddThirdPartyEndpointsReq.Merge(dst, src)
}
func (m *AddThirdPartyEndpointsReq) XXX_Size() int {
	return xxx_messageInfo_AddThirdPartyEndpointsReq.Size(m)
}
func (m *AddThirdPartyEndpointsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddThirdPartyEndpointsReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddThirdPartyEndpointsReq proto.InternalMessageInfo

func (m *AddThirdPartyEndpointsReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddThirdPartyEndpointsReq) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *AddThirdPartyEndpointsReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AddThirdPartyEndpointsReq) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *AddThirdPartyEndpointsReq) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

type UpdThirdPartyEndpointsReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	IsOnline             bool     `protobuf:"varint,5,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdThirdPartyEndpointsReq) Reset()         { *m = UpdThirdPartyEndpointsReq{} }
func (m *UpdThirdPartyEndpointsReq) String() string { return proto.CompactTextString(m) }
func (*UpdThirdPartyEndpointsReq) ProtoMessage()    {}
func (*UpdThirdPartyEndpointsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{12}
}
func (m *UpdThirdPartyEndpointsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdThirdPartyEndpointsReq.Unmarshal(m, b)
}
func (m *UpdThirdPartyEndpointsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdThirdPartyEndpointsReq.Marshal(b, m, deterministic)
}
func (dst *UpdThirdPartyEndpointsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdThirdPartyEndpointsReq.Merge(dst, src)
}
func (m *UpdThirdPartyEndpointsReq) XXX_Size() int {
	return xxx_messageInfo_UpdThirdPartyEndpointsReq.Size(m)
}
func (m *UpdThirdPartyEndpointsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdThirdPartyEndpointsReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdThirdPartyEndpointsReq proto.InternalMessageInfo

func (m *UpdThirdPartyEndpointsReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdThirdPartyEndpointsReq) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *UpdThirdPartyEndpointsReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *UpdThirdPartyEndpointsReq) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *UpdThirdPartyEndpointsReq) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

type DelThirdPartyEndpointsReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelThirdPartyEndpointsReq) Reset()         { *m = DelThirdPartyEndpointsReq{} }
func (m *DelThirdPartyEndpointsReq) String() string { return proto.CompactTextString(m) }
func (*DelThirdPartyEndpointsReq) ProtoMessage()    {}
func (*DelThirdPartyEndpointsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{13}
}
func (m *DelThirdPartyEndpointsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelThirdPartyEndpointsReq.Unmarshal(m, b)
}
func (m *DelThirdPartyEndpointsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelThirdPartyEndpointsReq.Marshal(b, m, deterministic)
}
func (dst *DelThirdPartyEndpointsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelThirdPartyEndpointsReq.Merge(dst, src)
}
func (m *DelThirdPartyEndpointsReq) XXX_Size() int {
	return xxx_messageInfo_DelThirdPartyEndpointsReq.Size(m)
}
func (m *DelThirdPartyEndpointsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelThirdPartyEndpointsReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelThirdPartyEndpointsReq proto.InternalMessageInfo

func (m *DelThirdPartyEndpointsReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DelThirdPartyEndpointsReq) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type ThirdPartyEndpoint struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	IsOnline             bool     `protobuf:"varint,6,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThirdPartyEndpoint) Reset()         { *m = ThirdPartyEndpoint{} }
func (m *ThirdPartyEndpoint) String() string { return proto.CompactTextString(m) }
func (*ThirdPartyEndpoint) ProtoMessage()    {}
func (*ThirdPartyEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{14}
}
func (m *ThirdPartyEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThirdPartyEndpoint.Unmarshal(m, b)
}
func (m *ThirdPartyEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThirdPartyEndpoint.Marshal(b, m, deterministic)
}
func (dst *ThirdPartyEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThirdPartyEndpoint.Merge(dst, src)
}
func (m *ThirdPartyEndpoint) XXX_Size() int {
	return xxx_messageInfo_ThirdPartyEndpoint.Size(m)
}
func (m *ThirdPartyEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_ThirdPartyEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_ThirdPartyEndpoint proto.InternalMessageInfo

func (m *ThirdPartyEndpoint) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ThirdPartyEndpoint) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *ThirdPartyEndpoint) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ThirdPartyEndpoint) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ThirdPartyEndpoint) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ThirdPartyEndpoint) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

type ThirdPartyEndpoints struct {
	Obj                  []*ThirdPartyEndpoint `protobuf:"bytes,1,rep,name=obj,proto3" json:"obj,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ThirdPartyEndpoints) Reset()         { *m = ThirdPartyEndpoints{} }
func (m *ThirdPartyEndpoints) String() string { return proto.CompactTextString(m) }
func (*ThirdPartyEndpoints) ProtoMessage()    {}
func (*ThirdPartyEndpoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_runtime_server_52464b0f7eb03240, []int{15}
}
func (m *ThirdPartyEndpoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThirdPartyEndpoints.Unmarshal(m, b)
}
func (m *ThirdPartyEndpoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThirdPartyEndpoints.Marshal(b, m, deterministic)
}
func (dst *ThirdPartyEndpoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThirdPartyEndpoints.Merge(dst, src)
}
func (m *ThirdPartyEndpoints) XXX_Size() int {
	return xxx_messageInfo_ThirdPartyEndpoints.Size(m)
}
func (m *ThirdPartyEndpoints) XXX_DiscardUnknown() {
	xxx_messageInfo_ThirdPartyEndpoints.DiscardUnknown(m)
}

var xxx_messageInfo_ThirdPartyEndpoints proto.InternalMessageInfo

func (m *ThirdPartyEndpoints) GetObj() []*ThirdPartyEndpoint {
	if m != nil {
		return m.Obj
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*ServiceRequest)(nil), "pb.ServiceRequest")
	proto.RegisterType((*ServicesRequest)(nil), "pb.ServicesRequest")
	proto.RegisterType((*TenantRequest)(nil), "pb.TenantRequest")
	proto.RegisterType((*StatusMessage)(nil), "pb.StatusMessage")
	proto.RegisterMapType((map[string]string)(nil), "pb.StatusMessage.StatusEntry")
	proto.RegisterType((*DiskMessage)(nil), "pb.DiskMessage")
	proto.RegisterMapType((map[string]float64)(nil), "pb.DiskMessage.DisksEntry")
	proto.RegisterType((*ServiceAppPodList)(nil), "pb.ServiceAppPodList")
	proto.RegisterType((*ServiceAppPod)(nil), "pb.ServiceAppPod")
	proto.RegisterMapType((map[string]*Container)(nil), "pb.ServiceAppPod.ContainersEntry")
	proto.RegisterType((*Container)(nil), "pb.Container")
	proto.RegisterType((*DeployInfo)(nil), "pb.DeployInfo")
	proto.RegisterMapType((map[string]string)(nil), "pb.DeployInfo.EndpointsEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.DeployInfo.IngressesEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.DeployInfo.PodsEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.DeployInfo.ReplicatsetEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.DeployInfo.SecretsEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.DeployInfo.ServicesEntry")
	proto.RegisterType((*TenantResource)(nil), "pb.TenantResource")
	proto.RegisterType((*AddThirdPartyEndpointsReq)(nil), "pb.AddThirdPartyEndpointsReq")
	proto.RegisterType((*UpdThirdPartyEndpointsReq)(nil), "pb.UpdThirdPartyEndpointsReq")
	proto.RegisterType((*DelThirdPartyEndpointsReq)(nil), "pb.DelThirdPartyEndpointsReq")
	proto.RegisterType((*ThirdPartyEndpoint)(nil), "pb.ThirdPartyEndpoint")
	proto.RegisterType((*ThirdPartyEndpoints)(nil), "pb.ThirdPartyEndpoints")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppRuntimeSyncClient is the client API for AppRuntimeSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppRuntimeSyncClient interface {
	GetAppStatus(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*StatusMessage, error)
	GetAppPods(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceAppPodList, error)
	GetDeployInfo(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*DeployInfo, error)
	GetTenantResource(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*TenantResource, error)
	ListThirdPartyEndpoints(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ThirdPartyEndpoints, error)
	AddThirdPartyEndpoint(ctx context.Context, in *AddThirdPartyEndpointsReq, opts ...grpc.CallOption) (*Empty, error)
	UpdThirdPartyEndpoint(ctx context.Context, in *UpdThirdPartyEndpointsReq, opts ...grpc.CallOption) (*Empty, error)
	DelThirdPartyEndpoint(ctx context.Context, in *DelThirdPartyEndpointsReq, opts ...grpc.CallOption) (*Empty, error)
}

type appRuntimeSyncClient struct {
	cc *grpc.ClientConn
}

func NewAppRuntimeSyncClient(cc *grpc.ClientConn) AppRuntimeSyncClient {
	return &appRuntimeSyncClient{cc}
}

func (c *appRuntimeSyncClient) GetAppStatus(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*StatusMessage, error) {
	out := new(StatusMessage)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/GetAppStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) GetAppPods(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceAppPodList, error) {
	out := new(ServiceAppPodList)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/GetAppPods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) GetDeployInfo(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*DeployInfo, error) {
	out := new(DeployInfo)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/GetDeployInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) GetTenantResource(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*TenantResource, error) {
	out := new(TenantResource)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/GetTenantResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) ListThirdPartyEndpoints(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ThirdPartyEndpoints, error) {
	out := new(ThirdPartyEndpoints)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/ListThirdPartyEndpoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) AddThirdPartyEndpoint(ctx context.Context, in *AddThirdPartyEndpointsReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/AddThirdPartyEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) UpdThirdPartyEndpoint(ctx context.Context, in *UpdThirdPartyEndpointsReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/UpdThirdPartyEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) DelThirdPartyEndpoint(ctx context.Context, in *DelThirdPartyEndpointsReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/DelThirdPartyEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppRuntimeSyncServer is the server API for AppRuntimeSync service.
type AppRuntimeSyncServer interface {
	GetAppStatus(context.Context, *ServicesRequest) (*StatusMessage, error)
	GetAppPods(context.Context, *ServiceRequest) (*ServiceAppPodList, error)
	GetDeployInfo(context.Context, *ServiceRequest) (*DeployInfo, error)
	GetTenantResource(context.Context, *TenantRequest) (*TenantResource, error)
	ListThirdPartyEndpoints(context.Context, *ServiceRequest) (*ThirdPartyEndpoints, error)
	AddThirdPartyEndpoint(context.Context, *AddThirdPartyEndpointsReq) (*Empty, error)
	UpdThirdPartyEndpoint(context.Context, *UpdThirdPartyEndpointsReq) (*Empty, error)
	DelThirdPartyEndpoint(context.Context, *DelThirdPartyEndpointsReq) (*Empty, error)
}

func RegisterAppRuntimeSyncServer(s *grpc.Server, srv AppRuntimeSyncServer) {
	s.RegisterService(&_AppRuntimeSync_serviceDesc, srv)
}

func _AppRuntimeSync_GetAppStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).GetAppStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/GetAppStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).GetAppStatus(ctx, req.(*ServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_GetAppPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).GetAppPods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/GetAppPods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).GetAppPods(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_GetDeployInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).GetDeployInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/GetDeployInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).GetDeployInfo(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_GetTenantResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).GetTenantResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/GetTenantResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).GetTenantResource(ctx, req.(*TenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_ListThirdPartyEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).ListThirdPartyEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/ListThirdPartyEndpoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).ListThirdPartyEndpoints(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_AddThirdPartyEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddThirdPartyEndpointsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).AddThirdPartyEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/AddThirdPartyEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).AddThirdPartyEndpoint(ctx, req.(*AddThirdPartyEndpointsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_UpdThirdPartyEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdThirdPartyEndpointsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).UpdThirdPartyEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/UpdThirdPartyEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).UpdThirdPartyEndpoint(ctx, req.(*UpdThirdPartyEndpointsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_DelThirdPartyEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelThirdPartyEndpointsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).DelThirdPartyEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/DelThirdPartyEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).DelThirdPartyEndpoint(ctx, req.(*DelThirdPartyEndpointsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppRuntimeSync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AppRuntimeSync",
	HandlerType: (*AppRuntimeSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppStatus",
			Handler:    _AppRuntimeSync_GetAppStatus_Handler,
		},
		{
			MethodName: "GetAppPods",
			Handler:    _AppRuntimeSync_GetAppPods_Handler,
		},
		{
			MethodName: "GetDeployInfo",
			Handler:    _AppRuntimeSync_GetDeployInfo_Handler,
		},
		{
			MethodName: "GetTenantResource",
			Handler:    _AppRuntimeSync_GetTenantResource_Handler,
		},
		{
			MethodName: "ListThirdPartyEndpoints",
			Handler:    _AppRuntimeSync_ListThirdPartyEndpoints_Handler,
		},
		{
			MethodName: "AddThirdPartyEndpoint",
			Handler:    _AppRuntimeSync_AddThirdPartyEndpoint_Handler,
		},
		{
			MethodName: "UpdThirdPartyEndpoint",
			Handler:    _AppRuntimeSync_UpdThirdPartyEndpoint_Handler,
		},
		{
			MethodName: "DelThirdPartyEndpoint",
			Handler:    _AppRuntimeSync_DelThirdPartyEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app_runtime_server.proto",
}

func init() {
	proto.RegisterFile("app_runtime_server.proto", fileDescriptor_app_runtime_server_52464b0f7eb03240)
}

var fileDescriptor_app_runtime_server_52464b0f7eb03240 = []byte{
	// 1141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xdb, 0x6e, 0x1b, 0x37,
	0x10, 0xb5, 0xae, 0x96, 0x46, 0x96, 0x62, 0x33, 0x75, 0xb2, 0x56, 0x92, 0x26, 0xd9, 0x22, 0x85,
	0x1f, 0x0c, 0xb7, 0x75, 0x61, 0xc4, 0x71, 0x82, 0x16, 0x82, 0x6d, 0xb8, 0x02, 0x1c, 0xd7, 0x58,
	0x3b, 0xcf, 0xc2, 0x7a, 0x97, 0x71, 0x59, 0x6b, 0xb9, 0xec, 0x92, 0x6b, 0x40, 0x8f, 0xed, 0x2f,
	0xe4, 0xbf, 0x8a, 0x7c, 0x52, 0xc1, 0x21, 0xf7, 0xa2, 0x4b, 0x90, 0xaa, 0x2d, 0xd0, 0xb7, 0xd5,
	0x99, 0x73, 0x66, 0x38, 0x33, 0xe4, 0x90, 0x02, 0xc7, 0x17, 0x62, 0x94, 0xa4, 0x5c, 0xb1, 0x88,
	0x8e, 0x24, 0x4d, 0xee, 0x68, 0xb2, 0x2b, 0x92, 0x58, 0xc5, 0xa4, 0x2a, 0xae, 0xdd, 0x55, 0x68,
	0x9c, 0x44, 0x42, 0x4d, 0xdc, 0x6f, 0xa0, 0x77, 0x49, 0x93, 0x3b, 0x16, 0x50, 0x8f, 0xfe, 0x96,
	0x52, 0xa9, 0xc8, 0x13, 0x00, 0x69, 0x90, 0x11, 0x0b, 0x9d, 0xca, 0xb3, 0xca, 0x76, 0xdb, 0x6b,
	0x5b, 0x64, 0x18, 0xba, 0x7b, 0x70, 0xcf, 0x0a, 0x64, 0xa6, 0x78, 0x0a, 0x9d, 0x42, 0x21, 0xad,
	0x04, 0x72, 0x89, 0x74, 0x77, 0xa0, 0x7b, 0x45, 0xb9, 0xcf, 0x55, 0xa6, 0x78, 0x04, 0x6d, 0x85,
	0x40, 0x11, 0xa2, 0x65, 0x80, 0x61, 0xe8, 0xfe, 0x5e, 0x81, 0xee, 0xa5, 0xf2, 0x55, 0x2a, 0xdf,
	0x52, 0x29, 0xfd, 0x1b, 0x4a, 0xf6, 0xa1, 0x29, 0x11, 0x70, 0x2a, 0xcf, 0x6a, 0xdb, 0x9d, 0xbd,
	0x27, 0xbb, 0xe2, 0x7a, 0x77, 0x8a, 0x62, 0x7f, 0x9d, 0x70, 0x95, 0x4c, 0x3c, 0x4b, 0xee, 0xbf,
	0x82, 0x4e, 0x09, 0x26, 0xeb, 0x50, 0xbb, 0xa5, 0x13, 0x1b, 0x4e, 0x7f, 0x92, 0x2f, 0xa0, 0x71,
	0xe7, 0x8f, 0x53, 0xea, 0x54, 0x11, 0x33, 0x3f, 0x0e, 0xab, 0x07, 0x15, 0x77, 0x02, 0x9d, 0x63,
	0x26, 0x6f, 0xb3, 0x05, 0x7c, 0x0b, 0x8d, 0x90, 0xc9, 0xdb, 0x2c, 0x7e, 0x5f, 0xc7, 0x2f, 0xd9,
	0xf1, 0xdb, 0x06, 0x37, 0xc4, 0xfe, 0x01, 0x40, 0x01, 0x7e, 0x2e, 0x74, 0xa5, 0x1c, 0xfa, 0x10,
	0x36, 0x6c, 0x81, 0x07, 0x42, 0x5c, 0xc4, 0xe1, 0x19, 0x93, 0x8a, 0xbc, 0x80, 0xba, 0x88, 0xc3,
	0x2c, 0xfe, 0x06, 0xe6, 0x5f, 0x26, 0x79, 0x68, 0x76, 0xff, 0xac, 0x42, 0x77, 0x0a, 0xff, 0x4c,
	0x37, 0x75, 0x23, 0x42, 0x2a, 0xc6, 0xf1, 0x44, 0x5b, 0x4d, 0x15, 0x5a, 0x06, 0x18, 0x86, 0xba,
	0xaf, 0xd6, 0xa8, 0x26, 0x82, 0x3a, 0x35, 0xd3, 0x57, 0x03, 0x5d, 0x4d, 0x04, 0x25, 0x5b, 0xd0,
	0x12, 0x71, 0x38, 0xe2, 0x7e, 0x44, 0x9d, 0x3a, 0x5a, 0x57, 0x45, 0x1c, 0x9e, 0xfb, 0x11, 0x25,
	0x9b, 0xd0, 0xd4, 0x26, 0x26, 0x9c, 0x86, 0xa9, 0xad, 0x88, 0xc3, 0xa1, 0xd0, 0xcb, 0xd1, 0xb0,
	0xed, 0x66, 0xd3, 0x2c, 0x47, 0xc4, 0xa1, 0xe9, 0x13, 0x19, 0x00, 0x04, 0x31, 0x57, 0x3e, 0xe3,
	0x34, 0x91, 0xce, 0x2a, 0x26, 0xfb, 0x7c, 0x2e, 0xd9, 0xdd, 0xa3, 0x9c, 0x63, 0x6a, 0x5e, 0x12,
	0xf5, 0xcf, 0xe0, 0xde, 0x8c, 0x79, 0x41, 0xf5, 0xbf, 0x2a, 0x57, 0xbf, 0xb3, 0xd7, 0xd5, 0x21,
	0x72, 0x55, 0xb9, 0x19, 0xef, 0xa0, 0x9d, 0xe3, 0xe4, 0x05, 0xf4, 0xf2, 0x40, 0x26, 0x69, 0xe3,
	0xb2, 0x9b, 0xa3, 0x98, 0xfa, 0x73, 0x58, 0x8b, 0x68, 0x14, 0x27, 0x93, 0xd1, 0x98, 0x45, 0x4c,
	0x61, 0x8c, 0x9a, 0xd7, 0x31, 0xd8, 0x99, 0x86, 0xdc, 0x8f, 0x4d, 0x80, 0x63, 0x53, 0x66, 0xfe,
	0x3e, 0x26, 0x8f, 0xa1, 0xad, 0xdd, 0x49, 0xe1, 0x07, 0x99, 0xcf, 0x02, 0x20, 0x2e, 0xac, 0xe9,
	0x7a, 0xd1, 0xf7, 0xe9, 0x98, 0x4a, 0xaa, 0x6c, 0x9b, 0xa6, 0x30, 0xf2, 0x25, 0xd8, 0xbe, 0x44,
	0x94, 0xab, 0xe9, 0x4e, 0x69, 0x84, 0xec, 0xd8, 0xfd, 0x53, 0xc7, 0x92, 0x3a, 0xb8, 0x7f, 0xf3,
	0xf8, 0xbb, 0x17, 0x71, 0x68, 0x2b, 0x89, 0x2c, 0x72, 0x00, 0x2d, 0xbb, 0x45, 0xa4, 0xd3, 0x40,
	0xc5, 0xe3, 0x19, 0x45, 0x36, 0x02, 0x8c, 0x2a, 0x67, 0x93, 0xd7, 0xd0, 0xa6, 0x3c, 0x14, 0x31,
	0xe3, 0x4a, 0xb7, 0x37, 0x3f, 0xac, 0x25, 0xe9, 0x49, 0x66, 0x37, 0xda, 0x82, 0x4f, 0xf6, 0x61,
	0x55, 0xd2, 0x20, 0xa1, 0x2a, 0x6b, 0xfd, 0xa3, 0xb9, 0xa8, 0x68, 0x35, 0xc2, 0x8c, 0xab, 0x63,
	0x32, 0x7e, 0x93, 0x50, 0x29, 0xa9, 0x74, 0x5a, 0x0b, 0x63, 0x0e, 0x33, 0xbb, 0x8d, 0x99, 0xf3,
	0xc9, 0x00, 0x3a, 0x09, 0x15, 0x63, 0x16, 0xf8, 0x4a, 0xd7, 0xb6, 0x8d, 0xf2, 0xa7, 0x33, 0x72,
	0xaf, 0x60, 0x18, 0x07, 0x65, 0x0d, 0x79, 0x90, 0x4f, 0x27, 0xc0, 0xba, 0x67, 0xe3, 0xe7, 0x25,
	0xb4, 0xf3, 0xc2, 0x2e, 0x33, 0x7c, 0xfa, 0xaf, 0xf3, 0x43, 0xfc, 0x0f, 0xc4, 0x6f, 0xa0, 0x37,
	0x5d, 0xe1, 0xa5, 0xd4, 0x87, 0xb0, 0x56, 0x2e, 0xf2, 0xb2, 0x91, 0xa7, 0xeb, 0xbc, 0x94, 0xfa,
	0x07, 0x58, 0x9f, 0x2d, 0xf3, 0x52, 0x13, 0xfb, 0x63, 0x0d, 0x7a, 0xd9, 0x25, 0x23, 0xe3, 0x34,
	0x09, 0xa8, 0x9e, 0x5f, 0x81, 0x48, 0x47, 0x89, 0xb9, 0x74, 0xd0, 0x4d, 0xcd, 0x83, 0x40, 0xa4,
	0xa5, 0x6b, 0x48, 0x13, 0xca, 0xc7, 0xb4, 0x15, 0x88, 0x14, 0xcf, 0xa8, 0x3e, 0xed, 0xf6, 0x18,
	0x67, 0x0e, 0x6a, 0xc8, 0xe8, 0x1a, 0x34, 0xf3, 0x31, 0x7b, 0xda, 0xeb, 0x73, 0xa7, 0x9d, 0x7c,
	0x0d, 0xf7, 0x92, 0x94, 0x73, 0xc6, 0x6f, 0x46, 0xfa, 0x52, 0xe6, 0x69, 0x84, 0x43, 0xb1, 0xe6,
	0x75, 0x2d, 0x3c, 0x10, 0xe2, 0x3c, 0x8d, 0x88, 0x0b, 0xdd, 0x94, 0xcb, 0x20, 0x1c, 0xd9, 0x55,
	0xe3, 0x7c, 0xac, 0x79, 0x1d, 0x04, 0x8f, 0x70, 0xd9, 0xda, 0x57, 0xc1, 0x31, 0x11, 0x57, 0x8d,
	0xaf, 0x8c, 0x65, 0x62, 0x6e, 0xc3, 0xba, 0xe1, 0x15, 0x39, 0x38, 0x2d, 0x24, 0xf6, 0x10, 0x7f,
	0x9b, 0x25, 0x41, 0x76, 0x80, 0x4c, 0x31, 0x8d, 0xd3, 0x36, 0x72, 0xd7, 0x4b, 0x5c, 0xe3, 0xf7,
	0x3b, 0xd8, 0x2c, 0xe7, 0xa2, 0x7e, 0x61, 0x49, 0x88, 0x19, 0x01, 0x0a, 0x48, 0x91, 0xd1, 0x95,
	0x36, 0xe9, 0xb4, 0x5e, 0x82, 0x53, 0x96, 0x30, 0xae, 0x68, 0xc2, 0xfd, 0x31, 0xaa, 0x3a, 0xa8,
	0xda, 0x2c, 0x54, 0x43, 0x6b, 0x3d, 0x4f, 0x23, 0xf7, 0x8f, 0x0a, 0x6c, 0x0d, 0xc2, 0x10, 0x1d,
	0x5d, 0xf8, 0x89, 0x9a, 0xe4, 0x1b, 0x5b, 0xaf, 0x9b, 0x40, 0x3d, 0x4d, 0xf3, 0x3b, 0x0d, 0xbf,
	0xf5, 0x86, 0x91, 0xf9, 0x45, 0xa6, 0x3f, 0x49, 0x0f, 0xaa, 0x4c, 0xd8, 0x81, 0x58, 0x65, 0x42,
	0xab, 0x44, 0x9c, 0x98, 0x36, 0x35, 0x3c, 0xfc, 0xd6, 0xdb, 0x80, 0xc9, 0x51, 0xcc, 0xc7, 0x8c,
	0x53, 0xec, 0x4c, 0xcb, 0x6b, 0x31, 0xf9, 0x33, 0xfe, 0xc6, 0x45, 0xbc, 0x13, 0xff, 0xf3, 0x22,
	0x06, 0xb0, 0x75, 0x4c, 0xc7, 0xff, 0x66, 0x0d, 0xee, 0x87, 0x0a, 0x90, 0x79, 0x07, 0xff, 0x61,
	0x02, 0xc5, 0x18, 0x6c, 0x94, 0xc7, 0xe0, 0x74, 0x62, 0xcd, 0x99, 0xc4, 0x7e, 0x84, 0xfb, 0x0b,
	0xb2, 0x22, 0xdb, 0x50, 0x8b, 0xaf, 0x7f, 0xb5, 0xaf, 0x9d, 0x07, 0x7a, 0x1a, 0xcf, 0xb3, 0x3c,
	0x4d, 0xd9, 0xfb, 0x50, 0x87, 0xde, 0x40, 0x08, 0xcf, 0x3c, 0x74, 0x2f, 0x27, 0x3c, 0x20, 0x07,
	0xb0, 0x76, 0x4a, 0xd5, 0x40, 0x08, 0xfb, 0xa8, 0xb8, 0x5f, 0x7a, 0x40, 0x64, 0x6f, 0xd6, 0xfe,
	0xc6, 0xdc, 0x13, 0xd2, 0x5d, 0x21, 0xaf, 0x00, 0x8c, 0x52, 0xcf, 0x6d, 0x42, 0x4a, 0xba, 0x4c,
	0xb6, 0x39, 0xf7, 0x18, 0xd1, 0xcf, 0x33, 0x77, 0x85, 0xec, 0x43, 0xf7, 0x94, 0xaa, 0xd2, 0x9d,
	0xbe, 0x48, 0xdd, 0x9b, 0xbe, 0x57, 0xdc, 0x15, 0xf2, 0x06, 0x36, 0x4e, 0xa9, 0x9a, 0x99, 0x5b,
	0xb8, 0xb6, 0xa9, 0x07, 0x73, 0x9f, 0x94, 0x21, 0x43, 0x73, 0x57, 0xc8, 0x4f, 0xf0, 0x50, 0x87,
	0x5f, 0x54, 0xc1, 0x45, 0xe1, 0x1f, 0x2e, 0x2e, 0xa4, 0x74, 0x57, 0xc8, 0x11, 0x6c, 0x2e, 0x3c,
	0x69, 0x04, 0x6f, 0xd2, 0x4f, 0x1e, 0xc2, 0x7e, 0x5b, 0x9b, 0xcd, 0x3f, 0x09, 0x74, 0xb2, 0xf0,
	0xa4, 0x18, 0x27, 0x9f, 0x3c, 0x44, 0x73, 0x4e, 0x16, 0x6e, 0x75, 0x62, 0xef, 0xf4, 0xf1, 0xdf,
	0x70, 0x72, 0xdd, 0xc4, 0x7f, 0x3a, 0xdf, 0xff, 0x15, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x9a, 0x6a,
	0xed, 0x05, 0x0d, 0x00, 0x00,
}
