// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app_runtime_server.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PodStatus_Type int32

const (
	// PENDING means the pod has been accepted by the system, but one or more of the containers
	// has not been started. This includes time before being bound to a node, as well as time spent
	// pulling images onto the host.
	PodStatus_PENDING PodStatus_Type = 0
	// RUNNING means the pod has been bound to a node and all of the containers have been started.
	// At least one container is still running or is in the process of being restarted.
	PodStatus_RUNNING PodStatus_Type = 1
	// SUCCEEDED means that all containers in the pod have voluntarily terminated
	// with a container exit code of 0, and the system is not going to restart any of these containers.
	PodStatus_SUCCEEDED PodStatus_Type = 2
	// FAILED means that all containers in the pod have terminated, and at least one container has
	// terminated in a failure (exited with a non-zero exit code or was stopped by the system).
	PodStatus_FAILED PodStatus_Type = 3
	// UNKNOWN means that for some reason the state of the pod could not be obtained, typically due
	// to an error in communicating with the host of the pod.
	PodStatus_UNKNOWN    PodStatus_Type = 4
	PodStatus_TEMINATING PodStatus_Type = 5
	PodStatus_ABNORMAL   PodStatus_Type = 6
	PodStatus_INITIATING PodStatus_Type = 7
	PodStatus_SCHEDULING PodStatus_Type = 8
)

var PodStatus_Type_name = map[int32]string{
	0: "PENDING",
	1: "RUNNING",
	2: "SUCCEEDED",
	3: "FAILED",
	4: "UNKNOWN",
	5: "TEMINATING",
	6: "ABNORMAL",
	7: "INITIATING",
	8: "SCHEDULING",
}

var PodStatus_Type_value = map[string]int32{
	"PENDING":    0,
	"RUNNING":    1,
	"SUCCEEDED":  2,
	"FAILED":     3,
	"UNKNOWN":    4,
	"TEMINATING": 5,
	"ABNORMAL":   6,
	"INITIATING": 7,
	"SCHEDULING": 8,
}

func (x PodStatus_Type) String() string {
	return proto.EnumName(PodStatus_Type_name, int32(x))
}

func (PodStatus_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{19, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ServiceRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceRequest) Reset()         { *m = ServiceRequest{} }
func (m *ServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceRequest) ProtoMessage()    {}
func (*ServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{1}
}

func (m *ServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRequest.Unmarshal(m, b)
}
func (m *ServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRequest.Marshal(b, m, deterministic)
}
func (m *ServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRequest.Merge(m, src)
}
func (m *ServiceRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceRequest.Size(m)
}
func (m *ServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRequest proto.InternalMessageInfo

func (m *ServiceRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type ServicesRequest struct {
	ServiceIds           string   `protobuf:"bytes,1,opt,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServicesRequest) Reset()         { *m = ServicesRequest{} }
func (m *ServicesRequest) String() string { return proto.CompactTextString(m) }
func (*ServicesRequest) ProtoMessage()    {}
func (*ServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{2}
}

func (m *ServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServicesRequest.Unmarshal(m, b)
}
func (m *ServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServicesRequest.Marshal(b, m, deterministic)
}
func (m *ServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServicesRequest.Merge(m, src)
}
func (m *ServicesRequest) XXX_Size() int {
	return xxx_messageInfo_ServicesRequest.Size(m)
}
func (m *ServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServicesRequest proto.InternalMessageInfo

func (m *ServicesRequest) GetServiceIds() string {
	if m != nil {
		return m.ServiceIds
	}
	return ""
}

type TenantRequest struct {
	TenantId             string   `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantRequest) Reset()         { *m = TenantRequest{} }
func (m *TenantRequest) String() string { return proto.CompactTextString(m) }
func (*TenantRequest) ProtoMessage()    {}
func (*TenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{3}
}

func (m *TenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantRequest.Unmarshal(m, b)
}
func (m *TenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantRequest.Marshal(b, m, deterministic)
}
func (m *TenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantRequest.Merge(m, src)
}
func (m *TenantRequest) XXX_Size() int {
	return xxx_messageInfo_TenantRequest.Size(m)
}
func (m *TenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TenantRequest proto.InternalMessageInfo

func (m *TenantRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

type StatusMessage struct {
	Status               map[string]string `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StatusMessage) Reset()         { *m = StatusMessage{} }
func (m *StatusMessage) String() string { return proto.CompactTextString(m) }
func (*StatusMessage) ProtoMessage()    {}
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{4}
}

func (m *StatusMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusMessage.Unmarshal(m, b)
}
func (m *StatusMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusMessage.Marshal(b, m, deterministic)
}
func (m *StatusMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusMessage.Merge(m, src)
}
func (m *StatusMessage) XXX_Size() int {
	return xxx_messageInfo_StatusMessage.Size(m)
}
func (m *StatusMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StatusMessage proto.InternalMessageInfo

func (m *StatusMessage) GetStatus() map[string]string {
	if m != nil {
		return m.Status
	}
	return nil
}

type DiskMessage struct {
	Disks                map[string]float64 `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DiskMessage) Reset()         { *m = DiskMessage{} }
func (m *DiskMessage) String() string { return proto.CompactTextString(m) }
func (*DiskMessage) ProtoMessage()    {}
func (*DiskMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{5}
}

func (m *DiskMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskMessage.Unmarshal(m, b)
}
func (m *DiskMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskMessage.Marshal(b, m, deterministic)
}
func (m *DiskMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskMessage.Merge(m, src)
}
func (m *DiskMessage) XXX_Size() int {
	return xxx_messageInfo_DiskMessage.Size(m)
}
func (m *DiskMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DiskMessage proto.InternalMessageInfo

func (m *DiskMessage) GetDisks() map[string]float64 {
	if m != nil {
		return m.Disks
	}
	return nil
}

type ServiceAppPodList struct {
	OldPods              []*ServiceAppPod `protobuf:"bytes,1,rep,name=oldPods,proto3" json:"oldPods,omitempty"`
	NewPods              []*ServiceAppPod `protobuf:"bytes,2,rep,name=newPods,proto3" json:"newPods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ServiceAppPodList) Reset()         { *m = ServiceAppPodList{} }
func (m *ServiceAppPodList) String() string { return proto.CompactTextString(m) }
func (*ServiceAppPodList) ProtoMessage()    {}
func (*ServiceAppPodList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{6}
}

func (m *ServiceAppPodList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceAppPodList.Unmarshal(m, b)
}
func (m *ServiceAppPodList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceAppPodList.Marshal(b, m, deterministic)
}
func (m *ServiceAppPodList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceAppPodList.Merge(m, src)
}
func (m *ServiceAppPodList) XXX_Size() int {
	return xxx_messageInfo_ServiceAppPodList.Size(m)
}
func (m *ServiceAppPodList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceAppPodList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceAppPodList proto.InternalMessageInfo

func (m *ServiceAppPodList) GetOldPods() []*ServiceAppPod {
	if m != nil {
		return m.OldPods
	}
	return nil
}

func (m *ServiceAppPodList) GetNewPods() []*ServiceAppPod {
	if m != nil {
		return m.NewPods
	}
	return nil
}

type ServiceAppPod struct {
	ServiceId            string                `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	DeployId             string                `protobuf:"bytes,2,opt,name=deploy_id,json=deployId,proto3" json:"deploy_id,omitempty"`
	DeployType           string                `protobuf:"bytes,3,opt,name=deploy_type,json=deployType,proto3" json:"deploy_type,omitempty"`
	PodName              string                `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodIp                string                `protobuf:"bytes,5,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	PodStatus            string                `protobuf:"bytes,6,opt,name=pod_status,json=podStatus,proto3" json:"pod_status,omitempty"`
	Containers           map[string]*Container `protobuf:"bytes,7,rep,name=containers,proto3" json:"containers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ServiceAppPod) Reset()         { *m = ServiceAppPod{} }
func (m *ServiceAppPod) String() string { return proto.CompactTextString(m) }
func (*ServiceAppPod) ProtoMessage()    {}
func (*ServiceAppPod) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{7}
}

func (m *ServiceAppPod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceAppPod.Unmarshal(m, b)
}
func (m *ServiceAppPod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceAppPod.Marshal(b, m, deterministic)
}
func (m *ServiceAppPod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceAppPod.Merge(m, src)
}
func (m *ServiceAppPod) XXX_Size() int {
	return xxx_messageInfo_ServiceAppPod.Size(m)
}
func (m *ServiceAppPod) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceAppPod.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceAppPod proto.InternalMessageInfo

func (m *ServiceAppPod) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *ServiceAppPod) GetDeployId() string {
	if m != nil {
		return m.DeployId
	}
	return ""
}

func (m *ServiceAppPod) GetDeployType() string {
	if m != nil {
		return m.DeployType
	}
	return ""
}

func (m *ServiceAppPod) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *ServiceAppPod) GetPodIp() string {
	if m != nil {
		return m.PodIp
	}
	return ""
}

func (m *ServiceAppPod) GetPodStatus() string {
	if m != nil {
		return m.PodStatus
	}
	return ""
}

func (m *ServiceAppPod) GetContainers() map[string]*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type Container struct {
	ContainerName        string   `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	MemoryLimit          int64    `protobuf:"varint,2,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{8}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *Container) GetMemoryLimit() int64 {
	if m != nil {
		return m.MemoryLimit
	}
	return 0
}

type DeployInfo struct {
	Namespace            string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Statefuleset         string            `protobuf:"bytes,2,opt,name=statefuleset,proto3" json:"statefuleset,omitempty"`
	Deployment           string            `protobuf:"bytes,3,opt,name=deployment,proto3" json:"deployment,omitempty"`
	StartTime            string            `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Pods                 map[string]string `protobuf:"bytes,5,rep,name=pods,proto3" json:"pods,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Services             map[string]string `protobuf:"bytes,6,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Endpoints            map[string]string `protobuf:"bytes,7,rep,name=endpoints,proto3" json:"endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Secrets              map[string]string `protobuf:"bytes,8,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Ingresses            map[string]string `protobuf:"bytes,9,rep,name=ingresses,proto3" json:"ingresses,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Replicatset          map[string]string `protobuf:"bytes,10,rep,name=replicatset,proto3" json:"replicatset,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Status               string            `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeployInfo) Reset()         { *m = DeployInfo{} }
func (m *DeployInfo) String() string { return proto.CompactTextString(m) }
func (*DeployInfo) ProtoMessage()    {}
func (*DeployInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{9}
}

func (m *DeployInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployInfo.Unmarshal(m, b)
}
func (m *DeployInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployInfo.Marshal(b, m, deterministic)
}
func (m *DeployInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployInfo.Merge(m, src)
}
func (m *DeployInfo) XXX_Size() int {
	return xxx_messageInfo_DeployInfo.Size(m)
}
func (m *DeployInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeployInfo proto.InternalMessageInfo

func (m *DeployInfo) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeployInfo) GetStatefuleset() string {
	if m != nil {
		return m.Statefuleset
	}
	return ""
}

func (m *DeployInfo) GetDeployment() string {
	if m != nil {
		return m.Deployment
	}
	return ""
}

func (m *DeployInfo) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *DeployInfo) GetPods() map[string]string {
	if m != nil {
		return m.Pods
	}
	return nil
}

func (m *DeployInfo) GetServices() map[string]string {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *DeployInfo) GetEndpoints() map[string]string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *DeployInfo) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *DeployInfo) GetIngresses() map[string]string {
	if m != nil {
		return m.Ingresses
	}
	return nil
}

func (m *DeployInfo) GetReplicatset() map[string]string {
	if m != nil {
		return m.Replicatset
	}
	return nil
}

func (m *DeployInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type TenantResource struct {
	CpuRequest            int64    `protobuf:"varint,1,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	CpuLimit              int64    `protobuf:"varint,2,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryRequest         int64    `protobuf:"varint,3,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	MemoryLimit           int64    `protobuf:"varint,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	RunningAppNum         int64    `protobuf:"varint,5,opt,name=running_app_num,json=runningAppNum,proto3" json:"running_app_num,omitempty"`
	UnscdCpuReq           int64    `protobuf:"varint,6,opt,name=unscd_cpu_req,json=unscdCpuReq,proto3" json:"unscd_cpu_req,omitempty"`
	UnscdCpuLimit         int64    `protobuf:"varint,7,opt,name=unscd_cpu_limit,json=unscdCpuLimit,proto3" json:"unscd_cpu_limit,omitempty"`
	UnscdMemoryReq        int64    `protobuf:"varint,8,opt,name=unscd_memory_req,json=unscdMemoryReq,proto3" json:"unscd_memory_req,omitempty"`
	UnscdMemoryLimit      int64    `protobuf:"varint,9,opt,name=unscd_memory_limit,json=unscdMemoryLimit,proto3" json:"unscd_memory_limit,omitempty"`
	RunningAppThirdNum    int64    `protobuf:"varint,10,opt,name=running_app_third_num,json=runningAppThirdNum,proto3" json:"running_app_third_num,omitempty"`
	RunningAppInternalNum int64    `protobuf:"varint,11,opt,name=running_app_internal_num,json=runningAppInternalNum,proto3" json:"running_app_internal_num,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *TenantResource) Reset()         { *m = TenantResource{} }
func (m *TenantResource) String() string { return proto.CompactTextString(m) }
func (*TenantResource) ProtoMessage()    {}
func (*TenantResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{10}
}

func (m *TenantResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantResource.Unmarshal(m, b)
}
func (m *TenantResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantResource.Marshal(b, m, deterministic)
}
func (m *TenantResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantResource.Merge(m, src)
}
func (m *TenantResource) XXX_Size() int {
	return xxx_messageInfo_TenantResource.Size(m)
}
func (m *TenantResource) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantResource.DiscardUnknown(m)
}

var xxx_messageInfo_TenantResource proto.InternalMessageInfo

func (m *TenantResource) GetCpuRequest() int64 {
	if m != nil {
		return m.CpuRequest
	}
	return 0
}

func (m *TenantResource) GetCpuLimit() int64 {
	if m != nil {
		return m.CpuLimit
	}
	return 0
}

func (m *TenantResource) GetMemoryRequest() int64 {
	if m != nil {
		return m.MemoryRequest
	}
	return 0
}

func (m *TenantResource) GetMemoryLimit() int64 {
	if m != nil {
		return m.MemoryLimit
	}
	return 0
}

func (m *TenantResource) GetRunningAppNum() int64 {
	if m != nil {
		return m.RunningAppNum
	}
	return 0
}

func (m *TenantResource) GetUnscdCpuReq() int64 {
	if m != nil {
		return m.UnscdCpuReq
	}
	return 0
}

func (m *TenantResource) GetUnscdCpuLimit() int64 {
	if m != nil {
		return m.UnscdCpuLimit
	}
	return 0
}

func (m *TenantResource) GetUnscdMemoryReq() int64 {
	if m != nil {
		return m.UnscdMemoryReq
	}
	return 0
}

func (m *TenantResource) GetUnscdMemoryLimit() int64 {
	if m != nil {
		return m.UnscdMemoryLimit
	}
	return 0
}

func (m *TenantResource) GetRunningAppThirdNum() int64 {
	if m != nil {
		return m.RunningAppThirdNum
	}
	return 0
}

func (m *TenantResource) GetRunningAppInternalNum() int64 {
	if m != nil {
		return m.RunningAppInternalNum
	}
	return 0
}

type AddThirdPartyEndpointsReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	IsOnline             bool     `protobuf:"varint,5,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddThirdPartyEndpointsReq) Reset()         { *m = AddThirdPartyEndpointsReq{} }
func (m *AddThirdPartyEndpointsReq) String() string { return proto.CompactTextString(m) }
func (*AddThirdPartyEndpointsReq) ProtoMessage()    {}
func (*AddThirdPartyEndpointsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{11}
}

func (m *AddThirdPartyEndpointsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddThirdPartyEndpointsReq.Unmarshal(m, b)
}
func (m *AddThirdPartyEndpointsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddThirdPartyEndpointsReq.Marshal(b, m, deterministic)
}
func (m *AddThirdPartyEndpointsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddThirdPartyEndpointsReq.Merge(m, src)
}
func (m *AddThirdPartyEndpointsReq) XXX_Size() int {
	return xxx_messageInfo_AddThirdPartyEndpointsReq.Size(m)
}
func (m *AddThirdPartyEndpointsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddThirdPartyEndpointsReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddThirdPartyEndpointsReq proto.InternalMessageInfo

func (m *AddThirdPartyEndpointsReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddThirdPartyEndpointsReq) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *AddThirdPartyEndpointsReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AddThirdPartyEndpointsReq) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *AddThirdPartyEndpointsReq) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

type UpdThirdPartyEndpointsReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	IsOnline             bool     `protobuf:"varint,5,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdThirdPartyEndpointsReq) Reset()         { *m = UpdThirdPartyEndpointsReq{} }
func (m *UpdThirdPartyEndpointsReq) String() string { return proto.CompactTextString(m) }
func (*UpdThirdPartyEndpointsReq) ProtoMessage()    {}
func (*UpdThirdPartyEndpointsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{12}
}

func (m *UpdThirdPartyEndpointsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdThirdPartyEndpointsReq.Unmarshal(m, b)
}
func (m *UpdThirdPartyEndpointsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdThirdPartyEndpointsReq.Marshal(b, m, deterministic)
}
func (m *UpdThirdPartyEndpointsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdThirdPartyEndpointsReq.Merge(m, src)
}
func (m *UpdThirdPartyEndpointsReq) XXX_Size() int {
	return xxx_messageInfo_UpdThirdPartyEndpointsReq.Size(m)
}
func (m *UpdThirdPartyEndpointsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdThirdPartyEndpointsReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdThirdPartyEndpointsReq proto.InternalMessageInfo

func (m *UpdThirdPartyEndpointsReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdThirdPartyEndpointsReq) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *UpdThirdPartyEndpointsReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *UpdThirdPartyEndpointsReq) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *UpdThirdPartyEndpointsReq) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

type DelThirdPartyEndpointsReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelThirdPartyEndpointsReq) Reset()         { *m = DelThirdPartyEndpointsReq{} }
func (m *DelThirdPartyEndpointsReq) String() string { return proto.CompactTextString(m) }
func (*DelThirdPartyEndpointsReq) ProtoMessage()    {}
func (*DelThirdPartyEndpointsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{13}
}

func (m *DelThirdPartyEndpointsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelThirdPartyEndpointsReq.Unmarshal(m, b)
}
func (m *DelThirdPartyEndpointsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelThirdPartyEndpointsReq.Marshal(b, m, deterministic)
}
func (m *DelThirdPartyEndpointsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelThirdPartyEndpointsReq.Merge(m, src)
}
func (m *DelThirdPartyEndpointsReq) XXX_Size() int {
	return xxx_messageInfo_DelThirdPartyEndpointsReq.Size(m)
}
func (m *DelThirdPartyEndpointsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelThirdPartyEndpointsReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelThirdPartyEndpointsReq proto.InternalMessageInfo

func (m *DelThirdPartyEndpointsReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DelThirdPartyEndpointsReq) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type ThirdPartyEndpoint struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	IsOnline             bool     `protobuf:"varint,6,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThirdPartyEndpoint) Reset()         { *m = ThirdPartyEndpoint{} }
func (m *ThirdPartyEndpoint) String() string { return proto.CompactTextString(m) }
func (*ThirdPartyEndpoint) ProtoMessage()    {}
func (*ThirdPartyEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{14}
}

func (m *ThirdPartyEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThirdPartyEndpoint.Unmarshal(m, b)
}
func (m *ThirdPartyEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThirdPartyEndpoint.Marshal(b, m, deterministic)
}
func (m *ThirdPartyEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThirdPartyEndpoint.Merge(m, src)
}
func (m *ThirdPartyEndpoint) XXX_Size() int {
	return xxx_messageInfo_ThirdPartyEndpoint.Size(m)
}
func (m *ThirdPartyEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_ThirdPartyEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_ThirdPartyEndpoint proto.InternalMessageInfo

func (m *ThirdPartyEndpoint) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ThirdPartyEndpoint) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *ThirdPartyEndpoint) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ThirdPartyEndpoint) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ThirdPartyEndpoint) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ThirdPartyEndpoint) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

type ThirdPartyEndpoints struct {
	Obj                  []*ThirdPartyEndpoint `protobuf:"bytes,1,rep,name=obj,proto3" json:"obj,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ThirdPartyEndpoints) Reset()         { *m = ThirdPartyEndpoints{} }
func (m *ThirdPartyEndpoints) String() string { return proto.CompactTextString(m) }
func (*ThirdPartyEndpoints) ProtoMessage()    {}
func (*ThirdPartyEndpoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{15}
}

func (m *ThirdPartyEndpoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThirdPartyEndpoints.Unmarshal(m, b)
}
func (m *ThirdPartyEndpoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThirdPartyEndpoints.Marshal(b, m, deterministic)
}
func (m *ThirdPartyEndpoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThirdPartyEndpoints.Merge(m, src)
}
func (m *ThirdPartyEndpoints) XXX_Size() int {
	return xxx_messageInfo_ThirdPartyEndpoints.Size(m)
}
func (m *ThirdPartyEndpoints) XXX_DiscardUnknown() {
	xxx_messageInfo_ThirdPartyEndpoints.DiscardUnknown(m)
}

var xxx_messageInfo_ThirdPartyEndpoints proto.InternalMessageInfo

func (m *ThirdPartyEndpoints) GetObj() []*ThirdPartyEndpoint {
	if m != nil {
		return m.Obj
	}
	return nil
}

type ListPodsBySIDReq struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPodsBySIDReq) Reset()         { *m = ListPodsBySIDReq{} }
func (m *ListPodsBySIDReq) String() string { return proto.CompactTextString(m) }
func (*ListPodsBySIDReq) ProtoMessage()    {}
func (*ListPodsBySIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{16}
}

func (m *ListPodsBySIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPodsBySIDReq.Unmarshal(m, b)
}
func (m *ListPodsBySIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPodsBySIDReq.Marshal(b, m, deterministic)
}
func (m *ListPodsBySIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPodsBySIDReq.Merge(m, src)
}
func (m *ListPodsBySIDReq) XXX_Size() int {
	return xxx_messageInfo_ListPodsBySIDReq.Size(m)
}
func (m *ListPodsBySIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPodsBySIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListPodsBySIDReq proto.InternalMessageInfo

func (m *ListPodsBySIDReq) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type GetPodDetailReq struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	PodName              string   `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPodDetailReq) Reset()         { *m = GetPodDetailReq{} }
func (m *GetPodDetailReq) String() string { return proto.CompactTextString(m) }
func (*GetPodDetailReq) ProtoMessage()    {}
func (*GetPodDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{17}
}

func (m *GetPodDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPodDetailReq.Unmarshal(m, b)
}
func (m *GetPodDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPodDetailReq.Marshal(b, m, deterministic)
}
func (m *GetPodDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPodDetailReq.Merge(m, src)
}
func (m *GetPodDetailReq) XXX_Size() int {
	return xxx_messageInfo_GetPodDetailReq.Size(m)
}
func (m *GetPodDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPodDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPodDetailReq proto.InternalMessageInfo

func (m *GetPodDetailReq) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *GetPodDetailReq) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

type PodEvent struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Age                  string   `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodEvent) Reset()         { *m = PodEvent{} }
func (m *PodEvent) String() string { return proto.CompactTextString(m) }
func (*PodEvent) ProtoMessage()    {}
func (*PodEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{18}
}

func (m *PodEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodEvent.Unmarshal(m, b)
}
func (m *PodEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodEvent.Marshal(b, m, deterministic)
}
func (m *PodEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodEvent.Merge(m, src)
}
func (m *PodEvent) XXX_Size() int {
	return xxx_messageInfo_PodEvent.Size(m)
}
func (m *PodEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PodEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PodEvent proto.InternalMessageInfo

func (m *PodEvent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PodEvent) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *PodEvent) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *PodEvent) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PodStatus struct {
	Type                 PodStatus_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PodStatus_Type" json:"type,omitempty"`
	Reason               string         `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Advice               string         `protobuf:"bytes,4,opt,name=advice,proto3" json:"advice,omitempty"`
	TypeStr              string         `protobuf:"bytes,5,opt,name=type_str,json=typeStr,proto3" json:"type_str,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PodStatus) Reset()         { *m = PodStatus{} }
func (m *PodStatus) String() string { return proto.CompactTextString(m) }
func (*PodStatus) ProtoMessage()    {}
func (*PodStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{19}
}

func (m *PodStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodStatus.Unmarshal(m, b)
}
func (m *PodStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodStatus.Marshal(b, m, deterministic)
}
func (m *PodStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodStatus.Merge(m, src)
}
func (m *PodStatus) XXX_Size() int {
	return xxx_messageInfo_PodStatus.Size(m)
}
func (m *PodStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PodStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PodStatus proto.InternalMessageInfo

func (m *PodStatus) GetType() PodStatus_Type {
	if m != nil {
		return m.Type
	}
	return PodStatus_PENDING
}

func (m *PodStatus) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *PodStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PodStatus) GetAdvice() string {
	if m != nil {
		return m.Advice
	}
	return ""
}

func (m *PodStatus) GetTypeStr() string {
	if m != nil {
		return m.TypeStr
	}
	return ""
}

type PodContainer struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Reason               string   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Started              string   `protobuf:"bytes,4,opt,name=started,proto3" json:"started,omitempty"`
	LimitMemory          string   `protobuf:"bytes,5,opt,name=limit_memory,json=limitMemory,proto3" json:"limit_memory,omitempty"`
	LimitCpu             string   `protobuf:"bytes,6,opt,name=limit_cpu,json=limitCpu,proto3" json:"limit_cpu,omitempty"`
	RequestMemory        string   `protobuf:"bytes,7,opt,name=request_memory,json=requestMemory,proto3" json:"request_memory,omitempty"`
	RequestCpu           string   `protobuf:"bytes,8,opt,name=request_cpu,json=requestCpu,proto3" json:"request_cpu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodContainer) Reset()         { *m = PodContainer{} }
func (m *PodContainer) String() string { return proto.CompactTextString(m) }
func (*PodContainer) ProtoMessage()    {}
func (*PodContainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{20}
}

func (m *PodContainer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodContainer.Unmarshal(m, b)
}
func (m *PodContainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodContainer.Marshal(b, m, deterministic)
}
func (m *PodContainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodContainer.Merge(m, src)
}
func (m *PodContainer) XXX_Size() int {
	return xxx_messageInfo_PodContainer.Size(m)
}
func (m *PodContainer) XXX_DiscardUnknown() {
	xxx_messageInfo_PodContainer.DiscardUnknown(m)
}

var xxx_messageInfo_PodContainer proto.InternalMessageInfo

func (m *PodContainer) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *PodContainer) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *PodContainer) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *PodContainer) GetStarted() string {
	if m != nil {
		return m.Started
	}
	return ""
}

func (m *PodContainer) GetLimitMemory() string {
	if m != nil {
		return m.LimitMemory
	}
	return ""
}

func (m *PodContainer) GetLimitCpu() string {
	if m != nil {
		return m.LimitCpu
	}
	return ""
}

func (m *PodContainer) GetRequestMemory() string {
	if m != nil {
		return m.RequestMemory
	}
	return ""
}

func (m *PodContainer) GetRequestCpu() string {
	if m != nil {
		return m.RequestCpu
	}
	return ""
}

type PodDetail struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Node                 string          `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	StartTime            string          `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Status               *PodStatus      `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Ip                   string          `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	InitContainers       []*PodContainer `protobuf:"bytes,6,rep,name=init_containers,json=initContainers,proto3" json:"init_containers,omitempty"`
	Containers           []*PodContainer `protobuf:"bytes,7,rep,name=containers,proto3" json:"containers,omitempty"`
	Events               []*PodEvent     `protobuf:"bytes,8,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PodDetail) Reset()         { *m = PodDetail{} }
func (m *PodDetail) String() string { return proto.CompactTextString(m) }
func (*PodDetail) ProtoMessage()    {}
func (*PodDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94cf1a886c479d6, []int{21}
}

func (m *PodDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodDetail.Unmarshal(m, b)
}
func (m *PodDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodDetail.Marshal(b, m, deterministic)
}
func (m *PodDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodDetail.Merge(m, src)
}
func (m *PodDetail) XXX_Size() int {
	return xxx_messageInfo_PodDetail.Size(m)
}
func (m *PodDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_PodDetail.DiscardUnknown(m)
}

var xxx_messageInfo_PodDetail proto.InternalMessageInfo

func (m *PodDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PodDetail) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *PodDetail) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *PodDetail) GetStatus() *PodStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PodDetail) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *PodDetail) GetInitContainers() []*PodContainer {
	if m != nil {
		return m.InitContainers
	}
	return nil
}

func (m *PodDetail) GetContainers() []*PodContainer {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *PodDetail) GetEvents() []*PodEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.PodStatus_Type", PodStatus_Type_name, PodStatus_Type_value)
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*ServiceRequest)(nil), "pb.ServiceRequest")
	proto.RegisterType((*ServicesRequest)(nil), "pb.ServicesRequest")
	proto.RegisterType((*TenantRequest)(nil), "pb.TenantRequest")
	proto.RegisterType((*StatusMessage)(nil), "pb.StatusMessage")
	proto.RegisterMapType((map[string]string)(nil), "pb.StatusMessage.StatusEntry")
	proto.RegisterType((*DiskMessage)(nil), "pb.DiskMessage")
	proto.RegisterMapType((map[string]float64)(nil), "pb.DiskMessage.DisksEntry")
	proto.RegisterType((*ServiceAppPodList)(nil), "pb.ServiceAppPodList")
	proto.RegisterType((*ServiceAppPod)(nil), "pb.ServiceAppPod")
	proto.RegisterMapType((map[string]*Container)(nil), "pb.ServiceAppPod.ContainersEntry")
	proto.RegisterType((*Container)(nil), "pb.Container")
	proto.RegisterType((*DeployInfo)(nil), "pb.DeployInfo")
	proto.RegisterMapType((map[string]string)(nil), "pb.DeployInfo.EndpointsEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.DeployInfo.IngressesEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.DeployInfo.PodsEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.DeployInfo.ReplicatsetEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.DeployInfo.SecretsEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.DeployInfo.ServicesEntry")
	proto.RegisterType((*TenantResource)(nil), "pb.TenantResource")
	proto.RegisterType((*AddThirdPartyEndpointsReq)(nil), "pb.AddThirdPartyEndpointsReq")
	proto.RegisterType((*UpdThirdPartyEndpointsReq)(nil), "pb.UpdThirdPartyEndpointsReq")
	proto.RegisterType((*DelThirdPartyEndpointsReq)(nil), "pb.DelThirdPartyEndpointsReq")
	proto.RegisterType((*ThirdPartyEndpoint)(nil), "pb.ThirdPartyEndpoint")
	proto.RegisterType((*ThirdPartyEndpoints)(nil), "pb.ThirdPartyEndpoints")
	proto.RegisterType((*ListPodsBySIDReq)(nil), "pb.ListPodsBySIDReq")
	proto.RegisterType((*GetPodDetailReq)(nil), "pb.GetPodDetailReq")
	proto.RegisterType((*PodEvent)(nil), "pb.PodEvent")
	proto.RegisterType((*PodStatus)(nil), "pb.PodStatus")
	proto.RegisterType((*PodContainer)(nil), "pb.PodContainer")
	proto.RegisterType((*PodDetail)(nil), "pb.PodDetail")
}

func init() { proto.RegisterFile("app_runtime_server.proto", fileDescriptor_f94cf1a886c479d6) }

var fileDescriptor_f94cf1a886c479d6 = []byte{
	// 1619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xcd, 0x6e, 0x1b, 0x47,
	0x12, 0x16, 0xff, 0xc9, 0xa2, 0x48, 0x51, 0x6d, 0xcb, 0xa6, 0x69, 0x7b, 0x6d, 0xcf, 0xda, 0x86,
	0x80, 0x35, 0xb4, 0x5e, 0xed, 0x1a, 0x96, 0x7f, 0xe0, 0x05, 0x4d, 0x32, 0x32, 0x11, 0x89, 0x16,
	0x46, 0x12, 0x72, 0x24, 0x46, 0x9c, 0xb6, 0x32, 0x31, 0x67, 0xa6, 0x33, 0x3f, 0x0a, 0x78, 0x4c,
	0x0e, 0x79, 0x81, 0x5c, 0x73, 0xc9, 0xe3, 0xe4, 0x12, 0xe4, 0x4d, 0x72, 0xc9, 0x03, 0x04, 0x55,
	0xdd, 0x3d, 0x33, 0xfc, 0x31, 0x1c, 0x25, 0x01, 0x72, 0x9b, 0xae, 0xfe, 0xbe, 0xaa, 0xae, 0xea,
	0xea, 0xaa, 0x22, 0xa1, 0x6d, 0x09, 0x31, 0x0e, 0x62, 0x2f, 0x72, 0x5c, 0x3e, 0x0e, 0x79, 0x70,
	0xc1, 0x83, 0x1d, 0x11, 0xf8, 0x91, 0xcf, 0xf2, 0xe2, 0xcc, 0xa8, 0x40, 0x69, 0xe0, 0x8a, 0x68,
	0x66, 0xfc, 0x1b, 0x9a, 0xc7, 0x3c, 0xb8, 0x70, 0x26, 0xdc, 0xe4, 0x5f, 0xc6, 0x3c, 0x8c, 0xd8,
	0x6d, 0x80, 0x50, 0x4a, 0xc6, 0x8e, 0xdd, 0xce, 0xdd, 0xcd, 0x6d, 0xd7, 0xcc, 0x9a, 0x92, 0x0c,
	0x6d, 0x63, 0x17, 0x36, 0x14, 0x21, 0xd4, 0x8c, 0x3b, 0x50, 0x4f, 0x19, 0xa1, 0xa2, 0x40, 0x42,
	0x09, 0x8d, 0x47, 0xd0, 0x38, 0xe1, 0x9e, 0xe5, 0x45, 0x9a, 0x71, 0x13, 0x6a, 0x11, 0x09, 0x52,
	0x13, 0x55, 0x29, 0x18, 0xda, 0xc6, 0xd7, 0x39, 0x68, 0x1c, 0x47, 0x56, 0x14, 0x87, 0x87, 0x3c,
	0x0c, 0xad, 0x73, 0xce, 0x9e, 0x40, 0x39, 0x24, 0x41, 0x3b, 0x77, 0xb7, 0xb0, 0x5d, 0xdf, 0xbd,
	0xbd, 0x23, 0xce, 0x76, 0xe6, 0x20, 0x6a, 0x35, 0xf0, 0xa2, 0x60, 0x66, 0x2a, 0x70, 0xe7, 0x19,
	0xd4, 0x33, 0x62, 0xd6, 0x82, 0xc2, 0x7b, 0x3e, 0x53, 0xe6, 0xf0, 0x93, 0x5d, 0x85, 0xd2, 0x85,
	0x35, 0x8d, 0x79, 0x3b, 0x4f, 0x32, 0xb9, 0x78, 0x9e, 0xdf, 0xcb, 0x19, 0x33, 0xa8, 0xf7, 0x9d,
	0xf0, 0xbd, 0x3e, 0xc0, 0x63, 0x28, 0xd9, 0x4e, 0xf8, 0x5e, 0xdb, 0xef, 0xa0, 0xfd, 0xcc, 0x3e,
	0x7d, 0x2b, 0xe3, 0x12, 0xd8, 0xd9, 0x03, 0x48, 0x85, 0x1f, 0x33, 0x9d, 0xcb, 0x9a, 0x76, 0x61,
	0x53, 0x05, 0xb8, 0x2b, 0xc4, 0x91, 0x6f, 0x1f, 0x38, 0x61, 0xc4, 0xfe, 0x05, 0x15, 0x7f, 0x6a,
	0x1f, 0xf9, 0xb6, 0x3e, 0xc2, 0x26, 0x85, 0x20, 0x8b, 0x33, 0x35, 0x02, 0xc1, 0x1e, 0xff, 0x8a,
	0xc0, 0xf9, 0x0f, 0x82, 0x15, 0xc2, 0xf8, 0x29, 0x0f, 0x8d, 0xb9, 0xad, 0x8f, 0x24, 0x00, 0xde,
	0x9d, 0xcd, 0xc5, 0xd4, 0x9f, 0xe1, 0xae, 0x0c, 0x5c, 0x55, 0x0a, 0x86, 0x36, 0xa6, 0x82, 0xda,
	0x8c, 0x66, 0x82, 0xb7, 0x0b, 0x32, 0x15, 0xa4, 0xe8, 0x64, 0x26, 0x38, 0xbb, 0x01, 0x55, 0xe1,
	0xdb, 0x63, 0xcf, 0x72, 0x79, 0xbb, 0x48, 0xbb, 0x15, 0xe1, 0xdb, 0x23, 0xcb, 0xe5, 0x6c, 0x0b,
	0xca, 0xb8, 0xe5, 0x88, 0x76, 0x49, 0x5e, 0x87, 0xf0, 0xed, 0xa1, 0xc0, 0xe3, 0xa0, 0x58, 0x25,
	0x40, 0x59, 0x1e, 0x47, 0xf8, 0xb6, 0xbc, 0x5a, 0xd6, 0x05, 0x98, 0xf8, 0x5e, 0x64, 0x39, 0x1e,
	0x0f, 0xc2, 0x76, 0x85, 0xfc, 0xbd, 0xb7, 0xe4, 0xef, 0x4e, 0x2f, 0xc1, 0xc8, 0x6b, 0xca, 0x90,
	0x3a, 0x07, 0xb0, 0xb1, 0xb0, 0xbd, 0xe2, 0xc2, 0xfe, 0x99, 0xbd, 0xb0, 0xfa, 0x6e, 0x03, 0x4d,
	0x24, 0xac, 0xec, 0xfd, 0x9d, 0x42, 0x2d, 0x91, 0xb3, 0x07, 0xd0, 0x4c, 0x0c, 0x49, 0xa7, 0xa5,
	0xca, 0x46, 0x22, 0x25, 0xd7, 0xef, 0xc1, 0xba, 0xcb, 0x5d, 0x3f, 0x98, 0x8d, 0xa7, 0x8e, 0xeb,
	0x44, 0x64, 0xa3, 0x60, 0xd6, 0xa5, 0xec, 0x00, 0x45, 0xc6, 0x2f, 0x65, 0x80, 0xbe, 0x0c, 0xb3,
	0xf7, 0xce, 0x67, 0xb7, 0xa0, 0x86, 0xea, 0x42, 0x61, 0x4d, 0xb4, 0xce, 0x54, 0xc0, 0x0c, 0x58,
	0xc7, 0x78, 0xf1, 0x77, 0xf1, 0x94, 0x87, 0x3c, 0x52, 0xd7, 0x34, 0x27, 0x63, 0xff, 0x00, 0x75,
	0x2f, 0x2e, 0xf7, 0xa2, 0xf9, 0x9b, 0x42, 0x09, 0xa5, 0x41, 0x64, 0x05, 0xd1, 0x18, 0x2b, 0x88,
	0xba, 0xab, 0x1a, 0x49, 0x4e, 0x1c, 0x97, 0xb3, 0x47, 0x50, 0x14, 0x98, 0x61, 0x25, 0x8a, 0x78,
	0x9b, 0x5e, 0x44, 0x72, 0xbc, 0x1d, 0x4c, 0x2d, 0x19, 0x68, 0x42, 0xb1, 0x3d, 0xa8, 0xaa, 0x0c,
	0xc2, 0x2b, 0x44, 0xc6, 0xad, 0x05, 0x86, 0x2e, 0x2a, 0x92, 0x95, 0xa0, 0xd9, 0x0b, 0xa8, 0x71,
	0xcf, 0x16, 0xbe, 0xe3, 0x45, 0xfa, 0x7a, 0x6f, 0x2f, 0x50, 0x07, 0x7a, 0x5f, 0x72, 0x53, 0x3c,
	0x7b, 0x02, 0x95, 0x90, 0x4f, 0x02, 0x1e, 0x85, 0xed, 0x2a, 0x51, 0x6f, 0x2e, 0x59, 0xa5, 0x5d,
	0x49, 0xd4, 0x58, 0xb4, 0xe9, 0x78, 0xe7, 0x01, 0x0f, 0x43, 0x1e, 0xb6, 0x6b, 0x2b, 0x6d, 0x0e,
	0xf5, 0xbe, 0xb2, 0x99, 0xe0, 0x59, 0x17, 0xea, 0x01, 0x17, 0x53, 0x67, 0x62, 0x45, 0x18, 0x7a,
	0x20, 0xfa, 0x9d, 0x05, 0xba, 0x99, 0x22, 0xa4, 0x82, 0x2c, 0x87, 0x5d, 0x4b, 0xea, 0x5d, 0x9d,
	0xc2, 0xae, 0x0b, 0xda, 0x53, 0xa8, 0x25, 0x81, 0xbd, 0x4c, 0x39, 0xeb, 0xbc, 0x48, 0xde, 0xf8,
	0x1f, 0x20, 0xbf, 0x84, 0xe6, 0x7c, 0x84, 0x2f, 0xc5, 0x7e, 0x0e, 0xeb, 0xd9, 0x20, 0x5f, 0xd6,
	0xf2, 0x7c, 0x9c, 0x2f, 0xc5, 0x7e, 0x05, 0xad, 0xc5, 0x30, 0x5f, 0xaa, 0x07, 0xfc, 0x5c, 0x80,
	0xa6, 0x6e, 0x5b, 0xa1, 0x1f, 0x07, 0x13, 0x8e, 0xe5, 0x6d, 0x22, 0xe2, 0x71, 0x20, 0xdb, 0x18,
	0xa9, 0x29, 0x98, 0x30, 0x11, 0x71, 0xa6, 0xb1, 0x21, 0x20, 0xfb, 0x8a, 0xab, 0x13, 0x11, 0xd3,
	0x13, 0xc6, 0x62, 0xa0, 0x5e, 0xb9, 0x56, 0x50, 0x20, 0x44, 0x43, 0x4a, 0xb5, 0x8e, 0xc5, 0x62,
	0x50, 0x5c, 0x2a, 0x06, 0xec, 0x21, 0x6c, 0x04, 0xb1, 0xe7, 0x39, 0xde, 0xf9, 0x18, 0xdb, 0xbc,
	0x17, 0xbb, 0x54, 0x33, 0x0b, 0x66, 0x43, 0x89, 0xbb, 0x42, 0x8c, 0x62, 0x97, 0x19, 0xd0, 0x88,
	0xbd, 0x70, 0x62, 0x8f, 0xd5, 0xa9, 0xa9, 0x7c, 0x16, 0xcc, 0x3a, 0x09, 0x7b, 0x74, 0x6c, 0xd4,
	0x95, 0x62, 0xa4, 0xc5, 0x8a, 0xd4, 0xa5, 0x51, 0xd2, 0xe6, 0x36, 0xb4, 0x24, 0x2e, 0xf5, 0xa1,
	0x5d, 0x25, 0x60, 0x93, 0xe4, 0x87, 0xda, 0x09, 0xf6, 0x08, 0xd8, 0x1c, 0x52, 0x2a, 0xad, 0x11,
	0xb6, 0x95, 0xc1, 0x4a, 0xbd, 0xff, 0x81, 0xad, 0xac, 0x2f, 0xd1, 0xe7, 0x4e, 0x60, 0x93, 0x47,
	0x40, 0x04, 0x96, 0x7a, 0x74, 0x82, 0x5b, 0xe8, 0xd6, 0x53, 0x68, 0x67, 0x29, 0x8e, 0x17, 0xf1,
	0xc0, 0xb3, 0xa6, 0xc4, 0xaa, 0x13, 0x6b, 0x2b, 0x65, 0x0d, 0xd5, 0xee, 0x28, 0x76, 0x8d, 0x6f,
	0x72, 0x70, 0xa3, 0x6b, 0xdb, 0xa4, 0xe8, 0xc8, 0x0a, 0xa2, 0x59, 0x92, 0xd8, 0x78, 0x6e, 0x06,
	0xc5, 0x38, 0x4e, 0x5a, 0x1e, 0x7d, 0x63, 0xc2, 0x84, 0x49, 0x9f, 0xc3, 0x4f, 0xd6, 0x84, 0xbc,
	0x23, 0x54, 0xbd, 0xcc, 0x3b, 0x02, 0x59, 0xc2, 0x0f, 0xe4, 0x35, 0x95, 0x4c, 0xfa, 0xc6, 0x34,
	0x70, 0xc2, 0xb1, 0xef, 0x4d, 0x1d, 0x8f, 0xd3, 0xcd, 0x54, 0xcd, 0xaa, 0x13, 0xbe, 0xa5, 0x35,
	0x1d, 0xe2, 0x54, 0xfc, 0xcd, 0x87, 0xe8, 0xc2, 0x8d, 0x3e, 0x9f, 0xfe, 0x99, 0x33, 0x18, 0xdf,
	0xe5, 0x80, 0x2d, 0x2b, 0xf8, 0x0b, 0x1d, 0x48, 0xcb, 0x60, 0x29, 0x5b, 0x06, 0xe7, 0x1d, 0x2b,
	0x2f, 0x38, 0xf6, 0x7f, 0xb8, 0xb2, 0xc2, 0x2b, 0xb6, 0x0d, 0x05, 0xff, 0xec, 0x0b, 0x35, 0x3c,
	0x5d, 0xc3, 0x6a, 0xbc, 0x8c, 0x32, 0x11, 0x62, 0xdc, 0x87, 0x16, 0x8e, 0x5c, 0x58, 0x68, 0x5f,
	0xcf, 0x8e, 0x87, 0x7d, 0x0c, 0x88, 0x3a, 0x7f, 0x2e, 0x75, 0xfe, 0x15, 0x6c, 0xec, 0x73, 0x04,
	0xf5, 0x79, 0x64, 0x39, 0xd3, 0x95, 0xa0, 0xb9, 0x61, 0x27, 0x3f, 0x37, 0xec, 0x18, 0x67, 0x50,
	0x3d, 0xf2, 0xed, 0xc1, 0x05, 0x97, 0x11, 0xa3, 0x69, 0x49, 0x45, 0x0c, 0xbf, 0xd1, 0xf7, 0x80,
	0x5b, 0xa1, 0xef, 0x29, 0xa2, 0x5a, 0xa1, 0x11, 0xeb, 0x5c, 0x0f, 0x56, 0xf8, 0xc9, 0xda, 0x50,
	0x71, 0xe5, 0x18, 0xaa, 0xc2, 0xa4, 0x97, 0xc6, 0x0f, 0x79, 0xea, 0x17, 0x6a, 0x50, 0x7a, 0x98,
	0xb1, 0xd2, 0xdc, 0x65, 0x18, 0x82, 0x64, 0x73, 0x07, 0x67, 0xb3, 0x8f, 0x58, 0xce, 0xd8, 0x29,
	0xcc, 0xd9, 0x41, 0x86, 0x65, 0x63, 0x73, 0x51, 0x53, 0x82, 0x5a, 0xa1, 0xfb, 0xa8, 0x71, 0x1c,
	0x46, 0x81, 0x3e, 0x1a, 0xae, 0x8f, 0xa3, 0xc0, 0xf8, 0x36, 0x07, 0x45, 0x9a, 0x07, 0xeb, 0x50,
	0x39, 0x1a, 0x8c, 0xfa, 0xc3, 0xd1, 0x7e, 0x6b, 0x0d, 0x17, 0xe6, 0xe9, 0x68, 0x84, 0x8b, 0x1c,
	0x6b, 0x40, 0xed, 0xf8, 0xb4, 0xd7, 0x1b, 0x0c, 0xfa, 0x83, 0x7e, 0x2b, 0xcf, 0x00, 0xca, 0x9f,
	0x74, 0x87, 0x07, 0x83, 0x7e, 0xab, 0x80, 0xb8, 0xd3, 0xd1, 0xa7, 0xa3, 0xb7, 0x9f, 0x8d, 0x5a,
	0x45, 0xd6, 0x04, 0x38, 0x19, 0x1c, 0x0e, 0x47, 0xdd, 0x13, 0xe4, 0x95, 0xd8, 0x3a, 0x54, 0xbb,
	0xaf, 0x47, 0x6f, 0xcd, 0xc3, 0xee, 0x41, 0xab, 0x8c, 0xbb, 0xc3, 0xd1, 0xf0, 0x64, 0x28, 0x77,
	0x2b, 0xb8, 0x3e, 0xee, 0xbd, 0x19, 0xf4, 0x4f, 0x0f, 0x70, 0x5d, 0x35, 0x7e, 0xcd, 0xc1, 0xfa,
	0x91, 0x6f, 0xa7, 0x13, 0xdb, 0x55, 0x28, 0x39, 0x2e, 0x3a, 0x29, 0x6f, 0x43, 0x2e, 0x50, 0x4a,
	0xc3, 0x93, 0xee, 0x12, 0xb4, 0xc8, 0x84, 0xaa, 0xb0, 0x18, 0x2a, 0x1a, 0x94, 0xb8, 0xad, 0x67,
	0x5c, 0xb5, 0xc4, 0xda, 0x4e, 0xd5, 0x50, 0x95, 0x46, 0x15, 0x96, 0x3a, 0xc9, 0x64, 0x51, 0xc4,
	0xec, 0x96, 0x90, 0x89, 0x88, 0xd5, 0xb8, 0x5b, 0x25, 0x41, 0x4f, 0xc4, 0xd8, 0x42, 0x54, 0xef,
	0xd0, 0x1a, 0x2a, 0x72, 0x9e, 0x54, 0x52, 0xa5, 0xe3, 0x0e, 0xce, 0x20, 0x12, 0x86, 0x5a, 0xaa,
	0x72, 0xb8, 0x53, 0xa2, 0x9e, 0x88, 0x8d, 0xef, 0x65, 0x6a, 0xc8, 0xe4, 0xc5, 0x04, 0xcc, 0xcc,
	0xa6, 0xf4, 0x4d, 0x32, 0xdf, 0xd6, 0x0e, 0xd3, 0xf7, 0xc2, 0x48, 0x58, 0x58, 0x1c, 0x09, 0x1f,
	0x24, 0xef, 0xb5, 0x98, 0xce, 0xc8, 0x49, 0x8e, 0x25, 0xcf, 0x57, 0x3e, 0xfd, 0x52, 0xf2, 0xf4,
	0x9f, 0xc1, 0x86, 0xe3, 0xa1, 0xbf, 0xe9, 0x18, 0x2f, 0x47, 0xc4, 0x96, 0xe2, 0xa7, 0x63, 0x76,
	0x13, 0x81, 0xe9, 0xac, 0xce, 0x1e, 0xaf, 0x18, 0xfe, 0x97, 0x59, 0x19, 0x0c, 0xbb, 0x0f, 0x65,
	0x8e, 0x8f, 0x4e, 0x0f, 0x84, 0xeb, 0x0a, 0x4d, 0x2f, 0xd1, 0x54, 0x7b, 0xbb, 0x3f, 0x16, 0xa1,
	0xd9, 0x15, 0xc2, 0x94, 0x3f, 0x9f, 0x8f, 0x67, 0xde, 0x84, 0xed, 0xc1, 0xfa, 0x3e, 0x8f, 0xba,
	0x42, 0xa8, 0xe7, 0x74, 0x25, 0xf3, 0x1b, 0x43, 0xff, 0x12, 0xee, 0x6c, 0x2e, 0xfd, 0x30, 0x35,
	0xd6, 0xd8, 0x33, 0x00, 0xc9, 0xa4, 0x1f, 0x67, 0x2c, 0xc3, 0xd3, 0xb4, 0xad, 0xa5, 0xdf, 0x2b,
	0x58, 0x81, 0x8c, 0x35, 0xf6, 0x04, 0x1a, 0xfb, 0x3c, 0xca, 0x8c, 0xfd, 0xab, 0xd8, 0xcd, 0xf9,
	0xd9, 0xd2, 0x58, 0x63, 0x2f, 0x61, 0x73, 0x9f, 0x47, 0x0b, 0xb3, 0x0b, 0x9d, 0x6d, 0xee, 0x67,
	0x78, 0x87, 0x65, 0x45, 0x12, 0x66, 0xac, 0xb1, 0x37, 0x70, 0x1d, 0xcd, 0xaf, 0xaa, 0xa2, 0xab,
	0xcc, 0x5f, 0x5f, 0x5d, 0x4c, 0x43, 0x63, 0x8d, 0xf5, 0x60, 0x6b, 0x65, 0xb7, 0x65, 0x34, 0x4d,
	0x7f, 0xb0, 0x11, 0x77, 0x6a, 0xb8, 0x2d, 0xff, 0x9f, 0x20, 0x25, 0x2b, 0xbb, 0xa5, 0x54, 0xf2,
	0xc1, 0x46, 0xba, 0xa4, 0x64, 0x65, 0xbb, 0x63, 0x6a, 0xae, 0x9f, 0xfe, 0x1e, 0x25, 0xff, 0xa3,
	0x14, 0x48, 0x9f, 0x0d, 0xa5, 0xc0, 0x42, 0x17, 0xe8, 0xe8, 0xa4, 0x97, 0x12, 0x63, 0xed, 0xac,
	0x4c, 0xff, 0xba, 0xfc, 0xf7, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0x28, 0x09, 0xde, 0x91,
	0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppRuntimeSyncClient is the client API for AppRuntimeSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppRuntimeSyncClient interface {
	GetAppStatus(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*StatusMessage, error)
	GetAppPods(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceAppPodList, error)
	GetDeployInfo(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*DeployInfo, error)
	GetTenantResource(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*TenantResource, error)
	ListThirdPartyEndpoints(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ThirdPartyEndpoints, error)
	AddThirdPartyEndpoint(ctx context.Context, in *AddThirdPartyEndpointsReq, opts ...grpc.CallOption) (*Empty, error)
	UpdThirdPartyEndpoint(ctx context.Context, in *UpdThirdPartyEndpointsReq, opts ...grpc.CallOption) (*Empty, error)
	DelThirdPartyEndpoint(ctx context.Context, in *DelThirdPartyEndpointsReq, opts ...grpc.CallOption) (*Empty, error)
	GetPodDetail(ctx context.Context, in *GetPodDetailReq, opts ...grpc.CallOption) (*PodDetail, error)
}

type appRuntimeSyncClient struct {
	cc *grpc.ClientConn
}

func NewAppRuntimeSyncClient(cc *grpc.ClientConn) AppRuntimeSyncClient {
	return &appRuntimeSyncClient{cc}
}

func (c *appRuntimeSyncClient) GetAppStatus(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*StatusMessage, error) {
	out := new(StatusMessage)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/GetAppStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) GetAppPods(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceAppPodList, error) {
	out := new(ServiceAppPodList)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/GetAppPods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) GetDeployInfo(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*DeployInfo, error) {
	out := new(DeployInfo)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/GetDeployInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) GetTenantResource(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*TenantResource, error) {
	out := new(TenantResource)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/GetTenantResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) ListThirdPartyEndpoints(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ThirdPartyEndpoints, error) {
	out := new(ThirdPartyEndpoints)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/ListThirdPartyEndpoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) AddThirdPartyEndpoint(ctx context.Context, in *AddThirdPartyEndpointsReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/AddThirdPartyEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) UpdThirdPartyEndpoint(ctx context.Context, in *UpdThirdPartyEndpointsReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/UpdThirdPartyEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) DelThirdPartyEndpoint(ctx context.Context, in *DelThirdPartyEndpointsReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/DelThirdPartyEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appRuntimeSyncClient) GetPodDetail(ctx context.Context, in *GetPodDetailReq, opts ...grpc.CallOption) (*PodDetail, error) {
	out := new(PodDetail)
	err := c.cc.Invoke(ctx, "/pb.AppRuntimeSync/GetPodDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppRuntimeSyncServer is the server API for AppRuntimeSync service.
type AppRuntimeSyncServer interface {
	GetAppStatus(context.Context, *ServicesRequest) (*StatusMessage, error)
	GetAppPods(context.Context, *ServiceRequest) (*ServiceAppPodList, error)
	GetDeployInfo(context.Context, *ServiceRequest) (*DeployInfo, error)
	GetTenantResource(context.Context, *TenantRequest) (*TenantResource, error)
	ListThirdPartyEndpoints(context.Context, *ServiceRequest) (*ThirdPartyEndpoints, error)
	AddThirdPartyEndpoint(context.Context, *AddThirdPartyEndpointsReq) (*Empty, error)
	UpdThirdPartyEndpoint(context.Context, *UpdThirdPartyEndpointsReq) (*Empty, error)
	DelThirdPartyEndpoint(context.Context, *DelThirdPartyEndpointsReq) (*Empty, error)
	GetPodDetail(context.Context, *GetPodDetailReq) (*PodDetail, error)
}

func RegisterAppRuntimeSyncServer(s *grpc.Server, srv AppRuntimeSyncServer) {
	s.RegisterService(&_AppRuntimeSync_serviceDesc, srv)
}

func _AppRuntimeSync_GetAppStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).GetAppStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/GetAppStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).GetAppStatus(ctx, req.(*ServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_GetAppPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).GetAppPods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/GetAppPods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).GetAppPods(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_GetDeployInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).GetDeployInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/GetDeployInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).GetDeployInfo(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_GetTenantResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).GetTenantResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/GetTenantResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).GetTenantResource(ctx, req.(*TenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_ListThirdPartyEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).ListThirdPartyEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/ListThirdPartyEndpoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).ListThirdPartyEndpoints(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_AddThirdPartyEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddThirdPartyEndpointsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).AddThirdPartyEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/AddThirdPartyEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).AddThirdPartyEndpoint(ctx, req.(*AddThirdPartyEndpointsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_UpdThirdPartyEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdThirdPartyEndpointsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).UpdThirdPartyEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/UpdThirdPartyEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).UpdThirdPartyEndpoint(ctx, req.(*UpdThirdPartyEndpointsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_DelThirdPartyEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelThirdPartyEndpointsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).DelThirdPartyEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/DelThirdPartyEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).DelThirdPartyEndpoint(ctx, req.(*DelThirdPartyEndpointsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppRuntimeSync_GetPodDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeSyncServer).GetPodDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppRuntimeSync/GetPodDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeSyncServer).GetPodDetail(ctx, req.(*GetPodDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppRuntimeSync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AppRuntimeSync",
	HandlerType: (*AppRuntimeSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppStatus",
			Handler:    _AppRuntimeSync_GetAppStatus_Handler,
		},
		{
			MethodName: "GetAppPods",
			Handler:    _AppRuntimeSync_GetAppPods_Handler,
		},
		{
			MethodName: "GetDeployInfo",
			Handler:    _AppRuntimeSync_GetDeployInfo_Handler,
		},
		{
			MethodName: "GetTenantResource",
			Handler:    _AppRuntimeSync_GetTenantResource_Handler,
		},
		{
			MethodName: "ListThirdPartyEndpoints",
			Handler:    _AppRuntimeSync_ListThirdPartyEndpoints_Handler,
		},
		{
			MethodName: "AddThirdPartyEndpoint",
			Handler:    _AppRuntimeSync_AddThirdPartyEndpoint_Handler,
		},
		{
			MethodName: "UpdThirdPartyEndpoint",
			Handler:    _AppRuntimeSync_UpdThirdPartyEndpoint_Handler,
		},
		{
			MethodName: "DelThirdPartyEndpoint",
			Handler:    _AppRuntimeSync_DelThirdPartyEndpoint_Handler,
		},
		{
			MethodName: "GetPodDetail",
			Handler:    _AppRuntimeSync_GetPodDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app_runtime_server.proto",
}
