<?xml version="1.0" ?>

<!--
    Copyright (c) 2005-2014 Zeus Technology. All rights reserved.

-->

<definitions name="System.Cache"
 targetNamespace="http://soap.zeus.com/zxtm/1.0/"
 xmlns:zeusns="http://soap.zeus.com/zxtm/1.0/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
 xmlns="http://schemas.xmlsoap.org/wsdl/">
   
   <types>
      <xsd:schema targetNamespace='http://soap.zeus.com/zxtm/1.0/'
       xmlns='http://www.w3.org/2001/XMLSchema'
       xmlns:SOAP-ENC='http://schemas.xmlsoap.org/soap/encoding/'
       xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'>
         
         <xsd:complexType name="StringArray">
           <xsd:complexContent>
             <xsd:restriction base='SOAP-ENC:Array'>
              <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:string[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="StringArrayArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType="zeusns:StringArray[]"/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="System.Cache.CacheContent">
           <xsd:annotation>
             <xsd:documentation>This structure contains the basic information about an individual cache entry for a machine.
             </xsd:documentation>
           </xsd:annotation>
           <xsd:all>
            <xsd:element name="url" type="xsd:string">
               <xsd:annotation>
                 <xsd:documentation>The URL of the entry.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="time_used" type="xsd:dateTime">
               <xsd:annotation>
                 <xsd:documentation>The time that the entry was last used.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="time_expires" type="xsd:dateTime">
               <xsd:annotation>
                 <xsd:documentation>The time that the entry expires.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="hits" type="xsd:int">
               <xsd:annotation>
                 <xsd:documentation>The number of hits for the entry.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="num" type="xsd:int">
               <xsd:annotation>
                 <xsd:documentation>The number of variants of this entry in the cache.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="response_code" type="xsd:int">
               <xsd:annotation>
                 <xsd:documentation>The HTTP response code for this entry in the cache.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="versions" type="zeusns:StringArray">
               <xsd:annotation>
                 <xsd:documentation>The HTTP versions the entry is cached for.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="varys" type="zeusns:StringArray">
               <xsd:annotation>
                 <xsd:documentation>The set of request-header fields that determine if the cache entry may be
                 used for a particular request.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
           </xsd:all>
         </xsd:complexType>
         
         <xsd:complexType name="System.Cache.CacheContentArray">
            <xsd:complexContent>
               <xsd:restriction base='SOAP-ENC:Array'>
                  <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='zeusns:System.Cache.CacheContent[]'/>
               </xsd:restriction>
            </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="System.Cache.GlobalInfo">
           <xsd:annotation>
             <xsd:documentation>This structure contains the basic information about the content cache for a machine.
             </xsd:documentation>
           </xsd:annotation>
           <xsd:all>
             <xsd:element name="bytes_used" type="xsd:int">
               <xsd:annotation>
                 <xsd:documentation>The number of bytes of memory used by the cache.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="percent_used" type="xsd:float">
               <xsd:annotation>
                 <xsd:documentation>The percentage of the cache used.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="entries" type="xsd:int">
               <xsd:annotation>
                 <xsd:documentation>The number of entries in the cache.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="num_lookups" type="xsd:int">
               <xsd:annotation>
                 <xsd:documentation>The number of times a request has tried to get a page from the cache.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="num_hits" type="xsd:int">
               <xsd:annotation>
                 <xsd:documentation>The number of times a request has successfully been served from the cache.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
           </xsd:all>
         </xsd:complexType>
         
         <xsd:complexType name="booleanArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:boolean[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="booleanArrayArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType="zeusns:booleanArray[]"/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         
         <xsd:complexType name="doubleArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:double[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="intArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:int[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="longArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:long[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="unsignedIntArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:unsignedInt[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="unsignedLongArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:unsignedLong[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
      </xsd:schema>
   </types>
   
   <message name="clearWebCacheRequest"></message>
   
   <message name="clearWebCacheResponse"></message>
   
   <message name="getCacheContentRequest"></message>
   
   <message name="getCacheContentResponse">
      <part name="cache_content" type="zeusns:System.Cache.CacheContentArray" />
   </message>
   
   <message name="getGlobalCacheInfoRequest"></message>
   
   <message name="getGlobalCacheInfoResponse">
      <part name="globalinfo" type="zeusns:System.Cache.GlobalInfo" />
   </message>
   
   <portType name="System.CachePort">
      <operation name="clearWebCache">
         <documentation>
            Clear all entries from the Web Cache for this machine.
         </documentation>
         
         <input message="zeusns:clearWebCacheRequest"/>
         <output message="zeusns:clearWebCacheResponse"/>
      </operation>
      
      <operation name="getCacheContent">
         <documentation>
            Get information about the Web Cache entries for this machine.
         </documentation>
         
         <input message="zeusns:getCacheContentRequest"/>
         <output message="zeusns:getCacheContentResponse"/>
      </operation>
      
      <operation name="getGlobalCacheInfo">
         <documentation>
            Get the size of the Web Cache, the number of Web Cache entries and the percentage
                                       memory used by the Web Cache for this machine.
         </documentation>
         
         <input message="zeusns:getGlobalCacheInfoRequest"/>
         <output message="zeusns:getGlobalCacheInfoResponse"/>
      </operation>
   </portType>
   
   <binding name="System.CacheBinding" type="zeusns:System.CachePort">
      <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="clearWebCache">
         <soap:operation soapAction="http://soap.zeus.com/zxtm/1.0/System/Cache/clearWebCache"/>
         <documentation>
            Clear all entries from the Web Cache for this machine.
         </documentation>
         
         <input>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.0/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </input>
         <output>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.0/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </output>
      </operation>
      
      <operation name="getCacheContent">
         <soap:operation soapAction="http://soap.zeus.com/zxtm/1.0/System/Cache/getCacheContent"/>
         <documentation>
            Get information about the Web Cache entries for this machine.
         </documentation>
         
         <input>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.0/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </input>
         <output>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.0/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </output>
      </operation>
      
      <operation name="getGlobalCacheInfo">
         <soap:operation soapAction="http://soap.zeus.com/zxtm/1.0/System/Cache/getGlobalCacheInfo"/>
         <documentation>
            Get the size of the Web Cache, the number of Web Cache entries and the percentage
                                       memory used by the Web Cache for this machine.
         </documentation>
         
         <input>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.0/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </input>
         <output>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.0/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </output>
      </operation>
   </binding>
   
   <service name="System.Cache">
      <documentation>
         The System.Cache interface provides information about the content cache for a machine. 
                                        Using this interface, you can retrieve both individual cache entries and global cache
                                        data for a machine and delete all entries in the cache.
      </documentation>
      
      <port name="System.CachePort" binding="zeusns:System.CacheBinding">
         <soap:address location="https://admin_server:9090/soap"/>
      </port>
   </service>
   
</definitions>
