<?xml version="1.0" ?>

<!--
    Copyright (c) 2005-2014 Zeus Technology. All rights reserved.

-->

<definitions name="System.Cache"
 targetNamespace="http://soap.zeus.com/zxtm/1.2/"
 xmlns:zeusns_1_2="http://soap.zeus.com/zxtm/1.2/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
 xmlns="http://schemas.xmlsoap.org/wsdl/">
   
   <types>
      <xsd:schema targetNamespace='http://soap.zeus.com/zxtm/1.2/'
       xmlns='http://www.w3.org/2001/XMLSchema'
       xmlns:SOAP-ENC='http://schemas.xmlsoap.org/soap/encoding/'
       xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'>
         
         <xsd:complexType name="StringArray">
           <xsd:complexContent>
             <xsd:restriction base='SOAP-ENC:Array'>
              <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:string[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="StringArrayArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType="zeusns_1_2:StringArray[]"/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="System.Cache.CacheContent">
           <xsd:annotation>
             <xsd:documentation>This structure contains the basic information about an individual cache entry for a machine.
             </xsd:documentation>
           </xsd:annotation>
           <xsd:all>
            <xsd:element name="virtual_server" type="xsd:string">
               <xsd:annotation>
                 <xsd:documentation>The virtual server hosting the entry.</xsd:documentation>
               </xsd:annotation>
            </xsd:element>
            <xsd:element name="protocol" type="zeusns_1_2:System.Cache.Protocol">
               <xsd:annotation>
                 <xsd:documentation>The protocol of the entry: http or https.</xsd:documentation>
               </xsd:annotation>
            </xsd:element>
            <xsd:element name="host" type="xsd:string">
               <xsd:annotation>
                 <xsd:documentation>The host name of the entry.</xsd:documentation>
               </xsd:annotation>
            </xsd:element>
            <xsd:element name="path" type="xsd:string">
               <xsd:annotation>
                 <xsd:documentation>The path of the entry.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="time_used" type="xsd:dateTime">
               <xsd:annotation>
                 <xsd:documentation>The time that the entry was last used.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="time_expires" type="xsd:dateTime">
               <xsd:annotation>
                 <xsd:documentation>The time that the entry expires.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="hits" type="xsd:long">
               <xsd:annotation>
                 <xsd:documentation>The number of hits for the entry.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="num_variants" type="xsd:int">
               <xsd:annotation>
                 <xsd:documentation>The number of variants of this entry in the cache.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="response_code" type="xsd:int">
               <xsd:annotation>
                 <xsd:documentation>The HTTP response code for this entry in the cache.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="versions" type="zeusns_1_2:StringArray">
               <xsd:annotation>
                 <xsd:documentation>The HTTP versions the entry is cached for.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="varys" type="zeusns_1_2:StringArray">
               <xsd:annotation>
                 <xsd:documentation>The set of request-header fields that determine if the cache entry may be
                 used for a particular request.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
           </xsd:all>
         </xsd:complexType>
         
         <xsd:complexType name="System.Cache.CacheContentArray">
            <xsd:complexContent>
               <xsd:restriction base='SOAP-ENC:Array'>
                  <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='zeusns_1_2:System.Cache.CacheContent[]'/>
               </xsd:restriction>
            </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="System.Cache.CacheContentInfo">
           <xsd:annotation>
             <xsd:documentation>This structure contains the information about the cache content.
             </xsd:documentation>
           </xsd:annotation>
           <xsd:all>
            <xsd:element name="number_matching_items" type="xsd:int">
               <xsd:annotation>
                 <xsd:documentation>The total number of items matching the wildcards in a query.</xsd:documentation>
               </xsd:annotation>
            </xsd:element>
            <xsd:element name="size_matching_items" type="xsd:long">
               <xsd:annotation>
                 <xsd:documentation>The total size of the items matching the wildcards in a query.</xsd:documentation>
               </xsd:annotation>
            </xsd:element>
             <xsd:element name="matching_items" type="zeusns_1_2:System.Cache.CacheContentArray">
               <xsd:annotation>
                 <xsd:documentation>The set of individual entries in the cache that matched the query.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
           </xsd:all>
         </xsd:complexType>
         
         <xsd:complexType name="System.Cache.GlobalInfo">
           <xsd:annotation>
             <xsd:documentation>This structure contains the basic information about the content cache for a machine.
             </xsd:documentation>
           </xsd:annotation>
           <xsd:all>
             <xsd:element name="bytes_used" type="xsd:long">
               <xsd:annotation>
                 <xsd:documentation>The number of bytes of memory used by the cache.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="percent_used" type="xsd:float">
               <xsd:annotation>
                 <xsd:documentation>The percentage of the cache used.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="entries" type="xsd:int">
               <xsd:annotation>
                 <xsd:documentation>The number of entries in the cache.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="num_lookups" type="xsd:long">
               <xsd:annotation>
                 <xsd:documentation>The number of times a request has tried to get a page from the cache.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
             <xsd:element name="num_hits" type="xsd:long">
               <xsd:annotation>
                 <xsd:documentation>The number of times a request has successfully been served from the cache.</xsd:documentation>
               </xsd:annotation>
             </xsd:element>
           </xsd:all>
         </xsd:complexType>
         
         <xsd:simpleType name="System.Cache.Protocol">
           <xsd:annotation>
             <xsd:documentation>This enumeration defines the possible protocols for cache entries.</xsd:documentation>
           </xsd:annotation>
           <xsd:restriction base="xsd:string">
             <xsd:enumeration value="http">
               <xsd:annotation>
                  <xsd:documentation>The hypertext transfer protocol (port 80 by default).</xsd:documentation>
               </xsd:annotation>
             </xsd:enumeration>
             <xsd:enumeration value="https">
               <xsd:annotation>
                  <xsd:documentation>The hypertext transfer protocol secure (port 443 by default).</xsd:documentation>
               </xsd:annotation>
             </xsd:enumeration>
             <xsd:enumeration value="both">
               <xsd:annotation>
                  <xsd:documentation>This special value can be used as wildcard to match both http and https.  It is never returned by the methods in this interface.</xsd:documentation>
               </xsd:annotation>
             </xsd:enumeration>
           </xsd:restriction>
         </xsd:simpleType>
         
         <xsd:complexType name="System.Cache.ProtocolArray">
            <xsd:complexContent>
               <xsd:restriction base='SOAP-ENC:Array'>
                  <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='zeusns_1_2:System.Cache.Protocol[]'/>
               </xsd:restriction>
            </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="booleanArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:boolean[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="booleanArrayArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType="zeusns_1_2:booleanArray[]"/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         
         <xsd:complexType name="doubleArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:double[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="intArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:int[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="longArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:long[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="unsignedIntArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:unsignedInt[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
         
         <xsd:complexType name="unsignedLongArray">
           <xsd:complexContent>
            <xsd:restriction base='SOAP-ENC:Array'>
             <xsd:attribute ref='SOAP-ENC:arrayType' wsdl:arrayType='xsd:unsignedLong[]'/>
            </xsd:restriction>
           </xsd:complexContent>
         </xsd:complexType>
      </xsd:schema>
   </types>
   
   <message name="clearCacheContentItemsRequest">
      <part name="virtual_servers" type="zeusns_1_2:StringArray" />
      <part name="protocols" type="zeusns_1_2:System.Cache.ProtocolArray" />
      <part name="hosts" type="zeusns_1_2:StringArray" />
      <part name="items" type="zeusns_1_2:StringArray" />
   </message>
   
   <message name="clearCacheContentItemsResponse"></message>
   
   <message name="clearMatchingCacheContentRequest">
      <part name="protocol" type="zeusns_1_2:System.Cache.Protocol" />
      <part name="host_wildcard" type="xsd:string" />
      <part name="path_wildcard" type="xsd:string" />
   </message>
   
   <message name="clearMatchingCacheContentResponse"></message>
   
   <message name="clearWebCacheRequest"></message>
   
   <message name="clearWebCacheResponse"></message>
   
   <message name="getCacheContentRequest">
      <part name="protocol" type="zeusns_1_2:System.Cache.Protocol" />
      <part name="host_wildcard" type="xsd:string" />
      <part name="path_wildcard" type="xsd:string" />
      <part name="max_entries" type="xsd:int" />
   </message>
   
   <message name="getCacheContentResponse">
      <part name="cache_content" type="zeusns_1_2:System.Cache.CacheContentInfo" />
   </message>
   
   <message name="getGlobalCacheInfoRequest"></message>
   
   <message name="getGlobalCacheInfoResponse">
      <part name="globalinfo" type="zeusns_1_2:System.Cache.GlobalInfo" />
   </message>
   
   <portType name="System.CachePort">
      <operation name="clearCacheContentItems">
         <documentation>
            Delete individual items from the Web Cache.  All input arguments are
                        arrays of strings and only those items are deleted whose virtual server,
                        protocol, host and path attribute match all the corresponding values for
                        a given index into the arguments.
         </documentation>
         
         <input message="zeusns_1_2:clearCacheContentItemsRequest"/>
         <output message="zeusns_1_2:clearCacheContentItemsResponse"/>
      </operation>
      
      <operation name="clearMatchingCacheContent">
         <documentation>
            Delete the Web Cache entries matching the input arguments.
         </documentation>
         
         <input message="zeusns_1_2:clearMatchingCacheContentRequest"/>
         <output message="zeusns_1_2:clearMatchingCacheContentResponse"/>
      </operation>
      
      <operation name="clearWebCache">
         <documentation>
            Clear all entries from the Web Cache for this machine.
         </documentation>
         
         <input message="zeusns_1_2:clearWebCacheRequest"/>
         <output message="zeusns_1_2:clearWebCacheResponse"/>
      </operation>
      
      <operation name="getCacheContent">
         <documentation>
            Get information about the Web Cache entries matching the input arguments.
         </documentation>
         
         <input message="zeusns_1_2:getCacheContentRequest"/>
         <output message="zeusns_1_2:getCacheContentResponse"/>
      </operation>
      
      <operation name="getGlobalCacheInfo">
         <documentation>
            Get the size of the Web Cache, the number of Web Cache entries and the percentage
                        memory used by the Web Cache for this machine.
         </documentation>
         
         <input message="zeusns_1_2:getGlobalCacheInfoRequest"/>
         <output message="zeusns_1_2:getGlobalCacheInfoResponse"/>
      </operation>
   </portType>
   
   <binding name="System.CacheBinding" type="zeusns_1_2:System.CachePort">
      <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="clearCacheContentItems">
         <soap:operation soapAction="http://soap.zeus.com/zxtm/1.2/System/Cache/clearCacheContentItems"/>
         <documentation>
            Delete individual items from the Web Cache.  All input arguments are
                        arrays of strings and only those items are deleted whose virtual server,
                        protocol, host and path attribute match all the corresponding values for
                        a given index into the arguments.
         </documentation>
         
         <input>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.2/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </input>
         <output>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.2/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </output>
      </operation>
      
      <operation name="clearMatchingCacheContent">
         <soap:operation soapAction="http://soap.zeus.com/zxtm/1.2/System/Cache/clearMatchingCacheContent"/>
         <documentation>
            Delete the Web Cache entries matching the input arguments.
         </documentation>
         
         <input>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.2/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </input>
         <output>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.2/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </output>
      </operation>
      
      <operation name="clearWebCache">
         <soap:operation soapAction="http://soap.zeus.com/zxtm/1.2/System/Cache/clearWebCache"/>
         <documentation>
            Clear all entries from the Web Cache for this machine.
         </documentation>
         
         <input>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.2/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </input>
         <output>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.2/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </output>
      </operation>
      
      <operation name="getCacheContent">
         <soap:operation soapAction="http://soap.zeus.com/zxtm/1.2/System/Cache/getCacheContent"/>
         <documentation>
            Get information about the Web Cache entries matching the input arguments.
         </documentation>
         
         <input>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.2/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </input>
         <output>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.2/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </output>
      </operation>
      
      <operation name="getGlobalCacheInfo">
         <soap:operation soapAction="http://soap.zeus.com/zxtm/1.2/System/Cache/getGlobalCacheInfo"/>
         <documentation>
            Get the size of the Web Cache, the number of Web Cache entries and the percentage
                        memory used by the Web Cache for this machine.
         </documentation>
         
         <input>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.2/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </input>
         <output>
            <soap:body use="encoded" namespace="http://soap.zeus.com/zxtm/1.2/System/Cache/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </output>
      </operation>
   </binding>
   
   <service name="System.Cache">
      <documentation>
         The System.Cache interface provides information about the content cache for a machine. 
                                        Using this interface, you can retrieve both individual cache entries and global cache
                                        data, delete all entries in the cache, delete entries matching wildcards or delete
                                        individual entries.
      </documentation>
      
      <port name="System.CachePort" binding="zeusns_1_2:System.CacheBinding">
         <soap:address location="https://admin_server:9090/soap"/>
      </port>
   </service>
   
</definitions>
